import { celebrationArtwork } from "./celebrationArtwork.js";
// Local assets exported from the Ribbon Sketch Figma design.
export const ribbonAssets = {
  "imgPinkEnvelopeWithRedRibbon": "/images/birthday/ribbon-sketch/figma/a7ee2fd56f5ed0e5.png",
  "imgFlowingSatinRibbon": "/images/birthday/ribbon-sketch/figma/7cf559e62a04022f.png",
  "imgSatinRibbonBow": "/images/birthday/ribbon-sketch/figma/f686ddaae3e652fb.png",
  "imgInstantPhotograph": celebrationArtwork[0].src,
  "imgInstantPhotograph1": celebrationArtwork[1].src,
  "imgFlowingSatinRibbon1": "/images/birthday/ribbon-sketch/figma/069ea0c3324dbe29.png",
  "imgFilmPhotograph": celebrationArtwork[2].src,
  "imgFilmPhotograph1": celebrationArtwork[3].src,
  "imgFilmPhotograph2": celebrationArtwork[4].src,
  "imgFilmPhotograph3": celebrationArtwork[5].src,
  "imgInstantPhotograph2": celebrationArtwork[2].src,
  "imgInstantPhotograph3": celebrationArtwork[3].src,
  "imgInstantPhotograph4": celebrationArtwork[4].src,
  "imgInstantPhotograph5": celebrationArtwork[5].src,
  "imgInstantPhotograph6": celebrationArtwork[0].src,
  "imgInstantPhotograph7": celebrationArtwork[1].src,
  "imgInstantPhotograph8": celebrationArtwork[2].src,
  "imgInstantPhotograph9": celebrationArtwork[3].src,
  "imgInstantPhotograph10": celebrationArtwork[4].src,
  "imgInstantPhotograph11": celebrationArtwork[5].src,
  "imgInstantPhotograph12": celebrationArtwork[0].src,
  "imgRealisticCameraBody": "/images/birthday/ribbon-sketch/figma/bb7920de30500753.png",
  "imgLcdBirthdayPhotograph": celebrationArtwork[0].src,
  "imgInstantPhotograph13": celebrationArtwork[1].src,
  "imgInstantPhotograph14": celebrationArtwork[2].src,
  "imgRealisticCrtTelevisionBody": "/images/birthday/ribbon-sketch/figma/0408d0a6c0e57b78.png",
  "imgSelectedBirthdayPhotograph": celebrationArtwork[0].src,
  "imgFilmPhotograph4": celebrationArtwork[0].src,
  "imgFilmPhotograph5": celebrationArtwork[1].src,
  "imgFilmPhotograph6": celebrationArtwork[2].src,
  "imgFilmPhotograph7": celebrationArtwork[3].src,
  "imgFlowingSatinRibbon2": "/images/birthday/ribbon-sketch/figma/ee72b5e8e8b57073.png",
  "imgPhotorealisticPinkCompactCamera": "/images/birthday/ribbon-sketch/figma/9f7786498e8c0a5e.png",
  "imgSatinRibbonBow1": "/images/birthday/ribbon-sketch/figma/a29919ded5d83079.png",
  "imgSatinRibbonBow2": "/images/birthday/ribbon-sketch/figma/67bdfb501c038a15.png",
  "imgSatinRibbonBow3": "/images/birthday/ribbon-sketch/figma/ea87c1dae32e331e.png",
  "imgFlowingSatinRibbon3": "/images/birthday/ribbon-sketch/figma/8d1aef4e4093cec3.png",
  "imgInstantPhotograph15": celebrationArtwork[3].src,
  "imgInstantPhotograph16": celebrationArtwork[4].src,
  "imgInstantPhotograph17": celebrationArtwork[5].src,
  "imgSoftWovenPaper": "/images/birthday/ribbon-sketch/figma/778426b78451f62a.svg",
  "imgPause": "/images/birthday/ribbon-sketch/figma/4ce518b56c835a57.svg",
  "imgArrowDown": "/images/birthday/ribbon-sketch/figma/052b94a85003bb69.svg",
  "imgArrowDown1": "/images/birthday/ribbon-sketch/figma/019a5ac7dc471d0c.svg",
  "imgGinghamPaper": "/images/birthday/ribbon-sketch/figma/ea855e76da70afcd.svg",
  "imgRotateCcw": "/images/birthday/ribbon-sketch/figma/bd5c0bb277a1fecf.svg",
  "imgCamera": "/images/birthday/ribbon-sketch/figma/fc15fcf1bfaae8a1.svg",
  "imgZap": "/images/birthday/ribbon-sketch/figma/3c5f9cdc884ee6b7.svg",
  "imgBatteryFull": "/images/birthday/ribbon-sketch/figma/11f6c1410e7f35e3.svg",
  "imgEditableShutterButton": "/images/birthday/ribbon-sketch/figma/efa4c8a189d739c4.svg",
  "imgEditableControlWheel": "/images/birthday/ribbon-sketch/figma/87d461097ddb906f.svg",
  "imgSetControl": "/images/birthday/ribbon-sketch/figma/2ef65734eaa3ab79.svg",
  "imgRuledDiaryPaper": "/images/birthday/ribbon-sketch/figma/36734aeaa65814e8.svg",
  "imgChevronLeft": "/images/birthday/ribbon-sketch/figma/7d21cd7f686b9826.svg",
  "imgChevronRight": "/images/birthday/ribbon-sketch/figma/46802ef8dcc26ec5.svg",
  "imgCalendarPlus": "/images/birthday/ribbon-sketch/figma/1c24fe12c6f5361c.svg",
  "imgMapPin": "/images/birthday/ribbon-sketch/figma/2cd03b3070697b6e.svg",
  "imgRsvpWovenPaper": "/images/birthday/ribbon-sketch/figma/05566c70f526f7c2.svg",
  "imgCircleCheck": "/images/birthday/ribbon-sketch/figma/f305bcd610c3a2a8.svg",
  "imgCircle": "/images/birthday/ribbon-sketch/figma/aa1f3b6fd2c679f7.svg",
  "imgArrowUpRight": "/images/birthday/ribbon-sketch/figma/47dcd2402402c609.svg",
  "imgHandwrittenNoteRuling": "/images/birthday/ribbon-sketch/figma/581954bdfec0f20e.svg",
  "imgPencil": "/images/birthday/ribbon-sketch/figma/bc1f1f2559dd315f.svg",
  "imgHeart": "/images/birthday/ribbon-sketch/figma/5d08dc589d8a33c4.svg",
  "imgSoftBlushDottedPaper": "/images/birthday/ribbon-sketch/figma/05d323bf50b49628.svg"
};
export const ribbonPhotos = celebrationArtwork.map(art => art.src);
export const openedEnvelope = "/images/birthday/ribbon-sketch/figma/94b2776dc9145f06.png";

export const ribbonPhotoCaptions = Object.fromEntries(celebrationArtwork.map(art => [art.src, art.caption]));
