import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const imageExtension = /\.(png|jpe?g|webp|gif|svg|avif|ico)$/i;
const ignored = new Set(['node_modules', '.git', 'dist', 'build', 'output', 'design-proposals']);
function walk(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    const filename = path.join(directory, entry.name);
    return entry.isDirectory() ? (ignored.has(entry.name) ? [] : walk(filename)) : [filename];
  });
}
const files = walk(root);
const sources = files.filter(filename => /\.(jsx?|tsx?|json|css|html|md|txt)$/i.test(filename)
  && !filename.startsWith(path.join(root, 'scripts') + path.sep))
  .map(filename => ({ filename, text: fs.readFileSync(filename, 'utf8') }));

// Evaluate these pure data modules to include paths assembled by their helpers.
const registries = ['birthdayAssets', 'summerAssets', 'customClassicalThemes',
  'selectedBridalDesigns', 'poolBirthdayDesigns', 'comicBirthdayDesigns',
  'girlyBirthdayDesigns', 'cocktailBirthdayDesigns', 'pinkChampagneDesigns', 'separatedThemeAssets'];
let registryText = '';
for (const name of registries) {
  registryText += JSON.stringify(await import(new URL(`../src/invitations/data/${name}.js`, import.meta.url)));
}
const text = sources.map(source => source.text).join('\n') + registryText;
const dynamicPrefixes = new Set();
for (const source of sources) {
  const name = path.basename(source.filename).replace(/ 2(?=\.js$)/, '').replace(/\.js$/, '');
  if (registries.includes(name)) continue;
  for (const match of source.text.matchAll(/`(\/(?:images|custom-orders|logos)\/[^`]+)`/g)) {
    if (match[1].includes('${')) dynamicPrefixes.add(match[1].split('${')[0]);
  }
}
// This helper also returns a path from a function, rather than an exported record.
dynamicPrefixes.add('/images/wedding-themes/');
const unused = [];
const images = files.filter(filename => imageExtension.test(filename));
for (const filename of images) {
  const relative = path.relative(root, filename).split(path.sep).join('/');
  const basename = path.basename(filename);
  const publicUrl = relative.startsWith('public/') ? relative.slice('public'.length) : null;
  if (text.includes(basename) || (publicUrl && text.includes(publicUrl))) continue;
  // Retain responsive assets generated from the base image at runtime.
  if (publicUrl && basename.includes('-portrait.')
    && text.includes(basename.replace('-portrait.', '.'))) continue;
  // Unreferenced numbered copies cannot be generated by the current path helpers.
  if (publicUrl && !/ \d+\.[^.]+$/.test(basename)
    && [...dynamicPrefixes].some(prefix => publicUrl.startsWith(prefix))) continue;
  unused.push({ path: relative, bytes: fs.statSync(filename).size });
}
console.log(JSON.stringify({ scannedImages: images.length, unusedImages: unused.length,
  unusedBytes: unused.reduce((sum, image) => sum + image.bytes, 0),
  preservedDynamicPrefixes: [...dynamicPrefixes].sort(), unused }, null, 2));
