export const defaultLanguage = "ka";
export const languages = ["ka", "en"];
export const languageNames = { ka: "ქართული", en: "English" };

const themeCatalog = [
  ["birthday-classic-celebration", "კლასიკური დღესასწაული", "თბილი და მარადიული", "Classic Celebration", "Joyful & timeless"],
  ["birthday-floral-affair", "ყვავილოვანი საღამო", "დახვეწილი და ყვავილოვანი", "Floral Affair", "Refined & blooming"],
  ["birthday-retro-disco", "რეტრო პოპი", "მკვეთრი და მხიარული", "Retro Pop", "Bold & playful"],
  ["birthday-y2k-digital", "Y2K წვეულება", "ციფრული ნოსტალგია", "Y2K Party", "Digital nostalgia"],
  ["birthday-pink-glam", "ვარდისფერი გლამური", "ფერებით სავსე წვეულება", "Pink Glam", "A party in full color"],
  ["birthday-coquette", "კოკეტი", "ნაზი და ტკბილი", "Coquette", "Soft & sweet"],
  ["birthday-midnight-luxury", "შუაღამის ფუფუნება", "ღამის ელეგანტურობა", "Midnight Luxury", "After-dark elegance"],
  ["birthday-garden-party", "ბაღის წვეულება", "სიცოცხლითა და ყვავილებით სავსე", "Garden Party", "Fresh & floral"],
  ["birthday-neon-night", "ნეონის ღამე", "მუხტით სავსე ღამე", "Neon Night", "Electric & late"],
  ["birthday-pastel-dream", "პასტელის ოცნება", "ხალისიანი ფერები", "Pastel Dream", "Lighthearted color"],
  ["birthday-minimal-editorial", "თანამედროვე მინიმალიზმი", "თავდაჯერებული სიმარტივე", "Minimal Modern", "Quiet confidence"],
  ["birthday-tropical-summer", "ტროპიკული ზაფხული", "მზიანი და ცოცხალი", "Tropical Summer", "Sunlit & lively"],
  ["birthday-painted-summer", "მოხატული ზაფხული", "ხელით მოხატული სანაპირო", "Painted Summer", "Hand-painted coast"],
  ["birthday-beer-party", "ლუდის წვეულება", "თბილი საღამო ბარში", "Beer Party", "Warm bar nights"],
  ["wedding-timeless-white", "მარადიული თეთრი", "კლასიკური ელეგანტურობა", "Timeless White", "Classic elegance"],
  ["wedding-modern-editorial", "თანამედროვე სარედაქციო", "გრაფიკული და დახვეწილი", "Modern Editorial", "Graphic & refined"],
  ["wedding-romantic-garden", "რომანტიკული ბაღი", "ყვავილებით სავსე დღე", "Romantic Garden", "A day in bloom"],
  ["wedding-black-tie", "ბლექ ტაი", "საღამოს ოფიციალური ელეგანტურობა", "Black Tie", "Formal after dark"],
  ["wedding-tuscany", "ტოსკანა", "თბილი და მზიანი", "Tuscany", "Warm & sunlit"],
  ["wedding-coastal", "სანაპირო", "ზღვის ნაზი ჰაერი", "Coastal", "Soft sea air"],
  ["wedding-bohemian", "ბოჰემური", "ბუნებრივი და გულწრფელი", "Bohemian", "Earthy & heartfelt"],
  ["wedding-vintage-romance", "ვინტაჟური რომანტიკა", "ძველი დროის ხიბლი", "Vintage Romance", "Old-world charm"],
  ["wedding-celestial", "ვარსკვლავური", "ვარსკვლავებში დაწერილი", "Celestial", "Written in the stars"],
  ["wedding-modern-botanical", "თანამედროვე ბოტანიკა", "გამოკვეთილი სიმწვანე", "Modern Botanical", "Sculptural greenery"],
];

const themeDescriptions = [
  ["birthday-classic-celebration", "ტორტი, სანთლები და საყვარელი ადამიანები — დაბადების დღე, რომელიც ყოველთვის კარგია.", "თბილი · მხიარული · კლასიკური", "Cake, candles, and everyone you love in a timeless birthday setting.", "Warm · joyful · timeless"],
  ["birthday-floral-affair", "ვარდისფერი შროშანები, თბილი სპილოსძვლისფერი და ლამაზი შეკრება დაბადების დღისთვის.", "ყვავილოვანი · დახვეწილი · საზეიმო", "Lush pink lilies, warm ivory, and a birthday made for a beautiful gathering.", "Floral · refined · celebratory"],
  ["birthday-retro-disco", "დისკოს ბურთები, თბილი ფერები და საცეკვაო განწყობა.", "მხიარული · თბილი · ენერგიული", "Mirrorball nights, warm color, and a little dance-floor drama.", "Funky · warm · electric"],
  ["birthday-y2k-digital", "მბზინავი ფანჯრები და პიქსელური ვარსკვლავები ახალი ნოსტალგიისთვის.", "ქრომი · ციფრული · მხიარული", "Glossy windows and pixel stars for a new kind of nostalgia.", "Chrome · digital · playful"],
  ["birthday-pink-glam", "მბზინავი და თავდაჯერებული დაბადების დღე მოდური ხასიათით.", "მბზინავი · მკვეთრი · მოდური", "A fashion-forward birthday with sparkle and confidence.", "Glossy · bold · fashion"],
  ["birthday-coquette", "ნაზი ლენტები, დახვეწილი შრიფტი და ოცნებასავით დღესასწაული.", "ვარდისფერი · ნაზი · რომანტიკული", "Soft ribbons, delicate type, and a dreamy little celebration.", "Blush · delicate · romantic"],
  ["birthday-midnight-luxury", "შამპანურის დეტალები და საღამოს ელეგანტურობა.", "მუქი · დახვეწილი · მყუდრო", "Champagne details and a black-tie mood after dark.", "Dark · polished · intimate"],
  ["birthday-garden-party", "ღია ცის განწყობა სიმწვანითა და ნაზი დღის შუქით.", "ბოტანიკური · ცოცხალი · დახვეწილი", "An open-air feeling with greenery and soft daylight.", "Botanical · fresh · graceful"],
  ["birthday-neon-night", "ელექტრული ფერები და საცეკვაო მოედანი გვიან ღამემდე.", "ღამე · ნათელი · მკვეთრი", "Electric color and a dance floor that goes late.", "Nightlife · bright · bold"],
  ["birthday-pastel-dream", "ღრუბელივით რბილი ფერები და სიხარულით სავსე ფორმები.", "ჰაეროვანი · ტკბილი · ფერადი", "Cloud-soft color and rounded shapes full of joy.", "Airy · sweet · colorful"],
  ["birthday-minimal-editorial", "თავდაჯერებული ტიპოგრაფია და სივრცე, სადაც მომენტი სუნთქავს.", "ნეიტრალური · გრაფიკული · თანამედროვე", "Confident typography and space for the moment to breathe.", "Neutral · graphic · modern"],
  ["birthday-tropical-summer", "ციტრუსის ენერგია, აუზის ლურჯი და მთელი დღის მზე.", "ზაფხული · ციტრუსი · ცოცხალი", "Citrus energy, pool-blue color, and sunshine all day.", "Summer · citrus · lively"],
  ["birthday-painted-summer", "ზღვისპირა დღესასწაული აკვარელის, მზით გამთბარი ქაღალდისა და ნაზი ფერების ფონზე.", "ზღვისპირა · მოხატული · ჰაეროვანი", "A breezy seaside celebration in watercolor, sun-warmed paper, and soft coastal color.", "Coastal · painted · airy"],
  ["birthday-beer-party", "მყუდრო საღამო ბარში, კარგი ლუდითა და კიდევ უკეთესი მეგობრებით.", "ქარვისფერი · თავისუფალი · საღამოს", "A warm night at the bar with good beer and even better company.", "Amber · relaxed · after dark"],
  ["wedding-timeless-white", "სპილოსძვლისფერი სიმშვიდე და ადგილი ყოველი ძვირფასი დეტალისთვის.", "კლასიკური · ნათელი · დახვეწილი", "Quiet ivory elegance with room for every precious detail.", "Classic · light · graceful"],
  ["wedding-modern-editorial", "თანამედროვე სიყვარულის ისტორია შავისა და თეთრის მკვეთრ კონტრასტში.", "გრაფიკული · დახვეწილი · თანამედროვე", "A contemporary love story told in bold black and white.", "Graphic · refined · current"],
  ["wedding-romantic-garden", "ნაზი ყვავილები და მწვანე ბილიკები აყვავებული დღესასწაულისთვის.", "ყვავილოვანი · ნაზი · ჰაეროვანი", "Soft florals and green paths for a celebration in bloom.", "Floral · tender · airy"],
  ["wedding-black-tie", "საზეიმო საღამო სანთლების შუქითა და ოქროს ელფერით.", "საზეიმო · შთამბეჭდავი · ნათელი", "Formal evenings, candlelight, and a hint of gold.", "Formal · dramatic · luminous"],
  ["wedding-tuscany", "ტერაკოტის სითბო და ხმელთაშუა ზღვის მშვიდი განწყობა.", "თბილი · ბუნებრივი · ელეგანტური", "Terracotta warmth and an unhurried Mediterranean mood.", "Warm · rustic · elegant"],
  ["wedding-coastal", "ზღვის ჰაერი, რბილი ქვიშა და შუქი, რომელიც თითქოს არ ქრება.", "ჰაეროვანი · ნაზი · მშვიდი", "Sea air, soft sand, and light that seems to last forever.", "Breezy · pale · serene"],
  ["wedding-bohemian", "ბუნებრივი ტექსტურა და თავისუფალი, გულწრფელი სტილი.", "ბუნებრივი · თავისუფალი · თბილი", "Earthy texture and effortless, heartfelt style.", "Organic · relaxed · warm"],
  ["wedding-vintage-romance", "ძველი ქაღალდის ხიბლი და ზღაპრული დღესასწაულის განცდა.", "ნოსტალგიური · ორნამენტული · მყუდრო", "Antique-paper charm with a storybook sense of occasion.", "Nostalgic · ornate · intimate"],
  ["wedding-celestial", "ვერცხლისფერი თანავარსკვლავედები და ორი ადამიანისთვის შექმნილი ღამის ცა.", "ოცნებისეული · ღამის · მანათობელი", "Silver constellations and a night sky made for two.", "Dreamlike · midnight · glowing"],
  ["wedding-modern-botanical", "სუფთა ხაზები, ღრმა მწვანე და გამოკვეთილი ფოთლები.", "ბუნებრივი · მინიმალური · ცოცხალი", "Clean lines meet deep green and sculptural leaves.", "Natural · minimal · fresh"],
];

function themeCaptions(language) {
  const offset = languages.indexOf(language) * 2 + 1;
  return Object.fromEntries([...themeCatalog.flatMap(([id, ...values]) => [
    [`themes.${id}.name`, values[offset - 1]],
    [`themes.${id}.style`, values[offset]],
  ]), ...themeDescriptions.flatMap(([id, ...values]) => [
    [`themes.${id}.description`, values[offset - 1]],
    [`themes.${id}.mood`, values[offset]],
  ])]);
}

export const captions = {
  ka: {
    ...themeCaptions("ka"),
    "nav.home": "მთავარი", "nav.surprises": "სიურპრიზები", "nav.invitations": "მოსაწვევები", "nav.about": "ჩვენ შესახებ", "nav.contact": "კონტაქტი", "nav.main": "მთავარი მენიუ", "nav.brand": "11:11 მთავარი გვერდი", "nav.language": "ენა",
    "common.home": "მთავარი", "common.backHome": "მთავარზე დაბრუნება", "common.allEvents": "ყველა ღონისძიება", "common.exploreEvents": "ღონისძიებების ნახვა", "common.exploreDesign": "დიზაინის ნახვა", "common.exploreInvitations": "მოსაწვევების ნახვა", "common.preview": "წინასწარი ნახვა", "common.birthday": "დაბადების დღე", "common.wedding": "ქორწილი", "common.corporate": "კორპორატიული", "common.other": "სხვა დღესასწაულები", "common.eventCategory": "ღონისძიების კატეგორია", "common.design": "დიზაინი", "common.designs": "დიზაინი", "common.invitation": "მოსაწვევი", "common.invitations": "მოსაწვევები", "common.style": "სტილი", "common.theme": "თემა", "common.themes": "თემები",
    "home.hero.message": "შექმენი დაუვიწყარი მომენტები.", "home.hero.action": "აქციე ეს მომენტი განსაკუთრებულად++", "home.projects.title": "აირჩიე შენი მომენტი", "home.projects.description": "აირჩიე ღონისძიება, აღმოაჩინე დიზაინი და გააცოცხლე ის ადამიანებითა და დეტალებით.", "home.projects.index": "01 / ღონისძიებები", "home.possibilities.index": "02 / შესაძლებლობები", "home.possibilities.title": "რისი შექმნა შეგიძლია?", "home.possibilities.description": "დაიწყე მოსაწვევით. დაამატე ისტორიები, ღიმილი და ადამიანები, რომლებიც ამ დღეს შენად აქცევენ.", "home.invitations.index": "04 / მოსაწვევები", "home.invitations.title": "პირველი შთაბეჭდილება შექმენი.", "home.invitations.description": "განსხვავებული დიზაინი განსხვავებული განწყობისთვის.", "home.interactive.index": "05 / ყველაზე საინტერესო", "home.interactive.title": "ყველა ისტორიის ნაწილი ხდება.", "home.interactive.description": "11:11 მოსაწვევზე მეტია — იდეები, რომლებიც შენს ადამიანებს აახლოებს.", "home.final.title": "შენს მომენტს მნიშვნელობა მიანიჭე.", "home.final.description": "რაც უნდა იყოს მიზეზი, ეს დღე შენებური გახადე.",
    "about.title": "11:11-ის შესახებ", "about.description": "11:11 არის სივრცე იმ მომენტებისთვის, ადამიანებისა და დღესასწაულებისთვის, რომელთა დამახსოვრებაც გინდა.", "contact.title": "დაგვიკავშირდი", "contact.description": "ამ სივრცეს ჯერ ვამზადებთ. მალე დაბრუნდი და დაგვიკავშირდი.", "notFound.title": "გვერდი ვერ მოიძებნა", "notFound.description": "ეს გვერდი ჯერ არ არსებობს.", "project.notFound.title": "ღონისძიება ვერ მოიძებნა", "project.notFound.description": "ეს ღონისძიება აქ არ არის, მაგრამ კიდევ ბევრი რამ შეგიძლია აღმოაჩინო.", "project.comingSoon": "ეს გამოცდილება მალე დაემატება.", "project.exploreCategory": "კატეგორიის ნახვა",
    "project.birthday.description": "იზეიმე მისი ისტორია, საყვარელი ადამიანები და კიდევ ერთი წელი.", "project.wedding.description": "ლამაზი ციფრული სივრცე ერთი დღისა და მთელი ცხოვრების ისტორიებისთვის.", "project.corporate.description": "გახადე გუნდის შეხვედრები, პრეზენტაციები და ვახშმები დასამახსოვრებელი.", "project.other.description": "შექმენი სივრცე ყოველი მნიშვნელოვანი ეტაპისა და შენი იდეისთვის.", "project.genderReveal": "ბავშვის სქესის გაგება", "project.genderReveal.description": "მხიარული სიურპრიზი თანამედროვე, თამაშით სავსე განწყობით.", "project.bachelorette": "ქალების წვეულება", "project.bachelorette.description": "სტილური საღამო საყვარელ ადამიანებთან ერთად.", "project.christening": "ნათლობა", "project.christening.description": "მშვიდი დღესასწაული ძვირფასი დღისთვის.",
    "home.possibility.invitations.title": "ციფრული მოსაწვევები", "home.possibility.invitations.detail": "განწყობა ჯერ კიდევ დღესასწაულამდე შექმენი.", "home.possibility.birthday.title": "დაბადების დღის გამოცდილება", "home.possibility.birthday.detail": "იზეიმე მისი ისტორია და არა მხოლოდ თარიღი.", "home.possibility.wedding.title": "ქორწილის გვერდები", "home.possibility.wedding.detail": "სივრცე შენი ადამიანებისა და გეგმებისთვის.", "home.possibility.diary.title": "მეგობრობის დღიური", "home.possibility.diary.detail": "შეინახე ისტორიები, რომლებსაც მეგობრები ჰყვებიან.", "home.possibility.memories.title": "სტუმრების მოგონებები", "home.possibility.memories.detail": "შეაგროვე სიტყვები და მომენტები, რომელთა შენახვაც ღირს.", "home.possibility.games.title": "თამაშები და ვიქტორინები", "home.possibility.games.detail": "ყველა ჩართე მხიარულებაში.", "home.interactive.diary.description": "შეხედე მეგობრობას იმ ადამიანების თვალით, ვინც მას ქმნის.", "home.interactive.wishes.title": "დაბადების დღის სურვილები", "home.interactive.wishes.description": "შეაგროვე თბილი სიტყვები, რომლებსაც ისევ დაუბრუნდებიან.", "home.interactive.memories.title": "მოგონებები", "home.interactive.memories.description": "პატარა ისტორიები ხანგრძლივ მოგონებებად აქციე.",
    "invitations.eyebrow": "დიზაინების კოლექცია / 11:11", "invitations.title": "მოსაწვევი, რომლის შენახვაც მოუნდებათ.", "invitations.description": "იპოვე პირველი მისალმება, რომელიც შენს დღესასწაულს შეეფერება. აღმოაჩინე {count} განსხვავებული დიზაინი.", "invitations.filter": "მოსაწვევების გაფილტვრა", "invitations.styleFilter": "სტილის მიხედვით გაფილტვრა", "invitations.all": "ყველა", "invitations.allStyles": "ყველა სტილი", "invitations.collection": "კოლექცია", "invitations.birthday.title": "დაბადების დღის მოსაწვევები", "invitations.birthday.description": "კიდევ ერთი წლის, დაუვიწყარი საღამოებისა და საყვარელი ადამიანებისთვის.", "invitations.wedding.title": "ქორწილის მოსაწვევები", "invitations.wedding.description": "დღის პირველი ლამაზი შთაბეჭდილება, რომელიც მუდამ გემახსოვრება.", "invitations.empty.title": "ამ სტილს ჯერ დიზაინი არ შეესაბამება.", "invitations.empty.description": "სცადე სხვა სტილი ან დაათვალიერე მთელი კოლექცია.", "invitations.viewAllStyles": "ყველა სტილის ნახვა", "invitations.note": "ეს დიზაინის წინასწარი ნიმუშებია. სრულფასოვანი მოსაწვევები ღონისძიების შექმნისას იქნება ხელმისაწვდომი.", "invitations.notFound.title": "მოსაწვევი ვერ მოიძებნა", "invitations.notFound.description": "დაათვალიერე არსებული დიზაინები და იპოვე შენი დღესასწაულისთვის შესაფერისი.", "invitations.allInvitations": "ყველა მოსაწვევი", "invitations.sample": "მოსაწვევის ნიმუში", "invitations.showcase": "დიზაინის ჩვენება", "invitations.explainer": "ამ დიზაინის სამყაროს პირველი ხედვა. ქვემოთ აღმოაჩინე მისი შრიფტი, ფერები, დეტალები და ღონისძიების ელემენტები.", "invitations.colors": "თემის ფერები", "invitations.end.label": "იპოვე შენი პირველი მისალმება", "invitations.end.title": "აღმოაჩინე მთელი კოლექცია.", "invitations.end.action": "ყველა მოსაწვევის დიზაინი", "invitations.invited": "მოწვეული ხარ", "invitations.invites": "11:11 მოსაწვევები", "invitations.styles.cartoon": "ილუსტრაციული", "invitations.styles.dark": "მუქი", "invitations.styles.floral": "ყვავილოვანი", "invitations.styles.green": "მწვანე", "invitations.styles.light-neutral": "ღია ნეიტრალური", "invitations.styles.line-art": "ხაზოვანი გრაფიკა", "invitations.styles.metallic": "მეტალის ელეგანტურობა", "invitations.styles.pastel": "პასტელი", "invitations.styles.photographic": "ფოტოგრაფიული", "invitations.styles.earthy": "თბილი მიწის ტონები", "invitations.styles.brown": "ყავისფერი ტონები", "invitations.styles.animated": "ანიმაციური", "invitations.styles.retro": "რეტრო", "invitations.styles.coastal": "ზღვისპირა", "invitations.styles.neon": "ნეონი",
    "birthday.hero.label": "დაბადების დღე / 11:11", "birthday.hero.title": "კიდევ ერთი წელი", "birthday.hero.emphasis": "დაუვიწყარი გახადე.", "birthday.hero.description": "გულისხმიერი მოსაწვევები, გულწრფელი სიტყვები და პატარა ისტორიები, რომლებიც ადამიანს განსაკუთრებულად აგრძნობინებს თავს.", "birthday.exploreInvitations": "დაბადების დღის მოსაწვევების ნახვა", "birthday.art": "კიდევ ერთი წრე მზის გარშემო", "birthday.invitations.description": "დღესასწაულის პირველი მინიშნება, რომელიც ყველას ღიმილს მოჰგვრის.", "birthday.modules.label": "შენი ადამიანები, შენი არჩევანი", "birthday.modules.title": "დაამატე ის, რაც შენ გგავს", "birthday.modules.description": "მოსაწვევი, ღონისძიების გვერდი, უკუთვლა და გალერეა დასაწყისს ქმნის. სურვილისამებრ დაამატე დღიური, შეტყობინებები, თამაშები ან ვიქტორინა.", "birthday.modules.caption": "ერთი და იგივე მეგობრობის დღიური დაბადების დღის ორ დიზაინში.", "birthday.modules.link": "ნახე, როგორ მუშაობს მოდული", "birthday.wishes.label": "თბილი სიტყვები", "birthday.wishes.title": "დაბადების დღის სურვილები", "birthday.wishes.description": "პატარა შეტყობინება შეიძლება სამუდამო მოგონებად იქცეს.", "birthday.stories.label": "შეინახე ისტორიები", "birthday.stories.title": "კალენდარში ჩაწერილ თარიღზე მეტი", "birthday.stories.description": "დაუსვი მეგობრებს რამდენიმე კითხვა და დღესასწაული მათი თვალით დაინახე.", "birthday.gallery.label": "ფოტომოგონებები", "birthday.gallery.title": "შენი ადამიანების გალერეა", "birthday.gallery.description": "გულწრფელი კადრები, მხიარული არეულობა და ფოტოები, რომლებსაც ისევ დაუბრუნდები.", "birthday.games.label": "მალე", "birthday.games.title": "მხიარულება გრძელდება", "birthday.games.description": "პატარა თამაშები, რომლებიც ყველას ისტორიაში ჩართავს.", "birthday.cta.title": "მზად ხარ აღსანიშნავად?", "birthday.cta.text": "დაიწყე მოსაწვევით, რომელიც დაამახსოვრდებათ.",
    "birthday.gallery.goodTimes": "კარგი დრო", "birthday.gallery.ourPeople": "ჩვენი საყვარელი ადამიანები", "birthday.gallery.aria": "მომავალი ფოტომოგონებების გალერეის დეკორატიული ნიმუში",
    "wedding.hero.label": "ქორწილი / 11:11", "wedding.hero.line1": "ერთი დღე.", "wedding.hero.line2": "ერთი ისტორია.", "wedding.hero.emphasis": "შენი.", "wedding.hero.description": "სივრცე ადამიანებისთვის, დაპირებებისთვის და ლამაზი დეტალებისთვის, რომლებიც ამ დღეს შენად აქცევს.", "wedding.exploreInvitations": "ქორწილის მოსაწვევების ნახვა", "wedding.art": "ერთი მშვენიერი დღე", "wedding.invitations.description": "დღესასწაულის გააზრებული პირველი თავი.", "wedding.features.label": "სრული ისტორია", "wedding.features.title": "მოსაწვევზე მეტი", "wedding.features.description": "პატარა დეტალები, რომლებიც ყველას შენი დღის ნაწილად აგრძნობინებს თავს.", "wedding.messages.label": "შესანახი სიტყვები", "wedding.messages.title": "სიყვარულით სავსე სტუმრების წიგნი", "wedding.messages.description": "შეტყობინებები ადამიანებისგან, რომლებმაც შენი ისტორია ყველაზე კარგად იციან.", "wedding.cta.title": "დაე, ისტორია დაიწყოს.", "wedding.cta.text": "იპოვე მოსაწვევი, რომელიც შენს დღეს შეეფერება.",
    "experience.firstHello": "პირველი მისალმება", "experience.exploreAll.birthday": "დაბადების დღის ყველა მოსაწვევი", "experience.exploreAll.wedding": "ქორწილის ყველა მოსაწვევი",
  },
  en: {
    ...themeCaptions("en"),
    "nav.home": "Home", "nav.surprises": "Surprises", "nav.invitations": "Invitations", "nav.about": "About Us", "nav.contact": "Contact Us", "nav.main": "Main navigation", "nav.brand": "11:11 home", "nav.language": "Language",
    "common.home": "Home", "common.backHome": "Back to home", "common.allEvents": "All event types", "common.exploreEvents": "Explore event types", "common.exploreDesign": "Explore design", "common.exploreInvitations": "Explore invitations", "common.preview": "Preview", "common.birthday": "Birthday", "common.wedding": "Wedding", "common.corporate": "Corporate", "common.other": "Other Celebrations", "common.eventCategory": "Event category", "common.design": "design", "common.designs": "designs", "common.invitation": "invitation", "common.invitations": "invitations", "common.style": "Style", "common.theme": "Theme", "common.themes": "themes",
    "home.hero.message": "Make moments worth remembering.", "home.hero.action": "Make it count++", "home.projects.title": "Choose your moment", "home.projects.description": "Choose an event, discover a design, and make room for the people and details that bring it to life.", "home.projects.index": "01 / EVENT TYPES", "home.possibilities.index": "02 / POSSIBILITIES", "home.possibilities.title": "What can you create?", "home.possibilities.description": "Start with an invitation. Add the stories, smiles, and people that make it yours.", "home.invitations.index": "04 / INVITATIONS", "home.invitations.title": "Make a first impression.", "home.invitations.description": "Different designs for different kinds of magic.", "home.interactive.index": "05 / THE GOOD STUFF", "home.interactive.title": "Everyone becomes part of the story.", "home.interactive.description": "11:11 goes beyond the invite with ideas that bring your people closer.", "home.final.title": "Make your moment count.", "home.final.description": "Whatever the reason, make it feel like yours.",
    "about.title": "About 11:11", "about.description": "11:11 is a space for the moments, people, and celebrations you want to remember.", "contact.title": "Contact Us", "contact.description": "We’re getting this space ready. Come back soon to get in touch.", "notFound.title": "Page not found", "notFound.description": "That page isn’t here yet.", "project.notFound.title": "Experience not found", "project.notFound.description": "That experience isn’t here, but there is more to explore.", "project.comingSoon": "This experience is coming soon.", "project.exploreCategory": "Explore category",
    "project.birthday.description": "Celebrate their story, their people, and another trip around the sun.", "project.wedding.description": "A beautiful digital home for one day and a lifetime of stories.", "project.corporate.description": "Make team gatherings, launches, and private dinners memorable.", "project.other.description": "Make room for every meaningful milestone and all your own ideas.", "project.genderReveal": "Gender Reveal", "project.genderReveal.description": "A joyful surprise with a modern, playful feel.", "project.bachelorette": "Bachelorette Party", "project.bachelorette.description": "A stylish night for your favorite people.", "project.christening": "Christening", "project.christening.description": "A peaceful celebration for a cherished day.",
    "home.possibility.invitations.title": "Digital invitations", "home.possibility.invitations.detail": "Set the feeling before the day begins.", "home.possibility.birthday.title": "Birthday experiences", "home.possibility.birthday.detail": "Celebrate their story, not just the date.", "home.possibility.wedding.title": "Wedding pages", "home.possibility.wedding.detail": "A place for your people and your plans.", "home.possibility.diary.title": "Friendship Diary module", "home.possibility.diary.detail": "Keep the stories your friends tell.", "home.possibility.memories.title": "Guest memories", "home.possibility.memories.detail": "Collect words and moments worth saving.", "home.possibility.games.title": "Games & quizzes", "home.possibility.games.detail": "Bring everyone into the fun.", "home.interactive.diary.description": "See a friendship through the eyes of the people in it.", "home.interactive.wishes.title": "Birthday Wishes", "home.interactive.wishes.description": "Make a collection of kind words they can return to.", "home.interactive.memories.title": "Memories", "home.interactive.memories.description": "Turn little stories into something that lasts.",
    "invitations.eyebrow": "THE DESIGN COLLECTION / 11:11", "invitations.title": "An invitation they’ll want to keep.", "invitations.description": "Find a first hello that feels like your celebration. Explore {count} looks, each with its own point of view.", "invitations.filter": "Filter invitation templates", "invitations.styleFilter": "Filter by style", "invitations.all": "All", "invitations.allStyles": "All styles", "invitations.collection": "THE COLLECTION", "invitations.birthday.title": "Birthday invitations", "invitations.birthday.description": "For another year of stories, late nights, and all your favorite people.", "invitations.wedding.title": "Wedding invitations", "invitations.wedding.description": "A beautiful first glimpse of the day you’ll always remember.", "invitations.empty.title": "No designs match this style yet.", "invitations.empty.description": "Try another style, or browse the full collection.", "invitations.viewAllStyles": "View all styles", "invitations.note": "These are design previews. Full invitations will be part of the event creation experience.", "invitations.notFound.title": "Invitation not found", "invitations.notFound.description": "Explore the current designs and find one that feels like your celebration.", "invitations.allInvitations": "All invitations", "invitations.sample": "THE INVITATION SAMPLE", "invitations.showcase": "DESIGN SHOWCASE", "invitations.explainer": "A first look at the visual world of this design. Explore its type, colors, details, and event pieces below.", "invitations.colors": "Theme colors", "invitations.end.label": "FIND YOUR FIRST HELLO", "invitations.end.title": "Explore the full collection.", "invitations.end.action": "All invitation designs", "invitations.invited": "YOU’RE INVITED", "invitations.invites": "11:11 INVITES", "invitations.styles.cartoon": "Cartoonish", "invitations.styles.dark": "Dark", "invitations.styles.floral": "Floral", "invitations.styles.green": "Green", "invitations.styles.light-neutral": "Light neutrals", "invitations.styles.line-art": "Line art & graphics", "invitations.styles.metallic": "Metallic luxe", "invitations.styles.pastel": "Pastels", "invitations.styles.photographic": "Photographic", "invitations.styles.earthy": "Warm earth tones", "invitations.styles.brown": "Brown tones", "invitations.styles.animated": "Animated", "invitations.styles.retro": "Retro", "invitations.styles.coastal": "Coastal", "invitations.styles.neon": "Neon",
    "birthday.hero.label": "BIRTHDAY / 11:11", "birthday.hero.title": "Make another year", "birthday.hero.emphasis": "unforgettable.", "birthday.hero.description": "Thoughtful invitations, heartfelt words, and the little stories that make someone feel celebrated.", "birthday.exploreInvitations": "Explore birthday invitations", "birthday.art": "another trip around the sun", "birthday.invitations.description": "A first glimpse of the celebration, designed to make people smile before the day even begins.", "birthday.modules.label": "YOUR PEOPLE, YOUR WAY", "birthday.modules.title": "Add the parts that feel like you", "birthday.modules.description": "Invitation, event page, countdown, and gallery set the scene. Turn on a diary, messages, games, or a quiz when they fit your celebration.", "birthday.modules.caption": "The same Friendship Diary in two Birthday designs.", "birthday.modules.link": "See how the module works", "birthday.wishes.label": "KIND WORDS", "birthday.wishes.title": "Birthday wishes", "birthday.wishes.description": "A little message can become a memory you keep forever.", "birthday.stories.label": "KEEP THE STORIES", "birthday.stories.title": "More than a date on the calendar", "birthday.stories.description": "Give friends a few prompts and see the celebration through their eyes.", "birthday.gallery.label": "PHOTO MEMORIES", "birthday.gallery.title": "A gallery of all your people", "birthday.gallery.description": "The candid moments, the joyful chaos, the photos you come back to.", "birthday.games.label": "COMING LATER", "birthday.games.title": "The fun keeps going", "birthday.games.description": "Little games to bring everyone into the story.", "birthday.cta.title": "Ready to celebrate?", "birthday.cta.text": "Start with an invitation they’ll remember.",
    "birthday.gallery.goodTimes": "good times", "birthday.gallery.ourPeople": "our favorite people", "birthday.gallery.aria": "Decorative preview of a future photo memories gallery",
    "wedding.hero.label": "WEDDING / 11:11", "wedding.hero.line1": "One day.", "wedding.hero.line2": "One story.", "wedding.hero.emphasis": "Yours.", "wedding.hero.description": "A space for the people, promises, and beautiful details that make the day your own.", "wedding.exploreInvitations": "Explore wedding invitations", "wedding.art": "one beautiful day", "wedding.invitations.description": "A thoughtful first chapter for the celebration to come.", "wedding.features.label": "THE WHOLE STORY", "wedding.features.title": "More than an invitation", "wedding.features.description": "The little details that help everyone feel part of your day.", "wedding.messages.label": "WORDS TO KEEP", "wedding.messages.title": "A guest book full of love", "wedding.messages.description": "Messages from the people who know your story best.", "wedding.cta.title": "Let the story begin.", "wedding.cta.text": "Find the invitation that feels like your day.",
    "experience.firstHello": "THE FIRST HELLO", "experience.exploreAll.birthday": "Explore all birthday invitations", "experience.exploreAll.wedding": "Explore all wedding invitations",
  },
};

Object.assign(captions.ka, {
  "themeCanvas.aria": "{name} მოსაწვევის დიზაინი", "themeCanvas.birthdayInvite": "დაბადების დღის მოსაწვევი", "themeCanvas.weddingInvite": "ქორწილის მოსაწვევი", "themeCanvas.gallery.label": "03 / მომენტები", "themeCanvas.gallery.birthday.0": "საცეკვაო მოედანი", "themeCanvas.gallery.birthday.1": "ჩაიფიქრე სურვილი", "themeCanvas.gallery.birthday.2": "ჩვენი ადამიანები", "themeCanvas.gallery.birthday.3": "კიდევ ერთი სადღეგრძელო", "themeCanvas.gallery.wedding.0": "ერთად", "themeCanvas.gallery.wedding.1": "სუფრა", "themeCanvas.gallery.wedding.2": "დაპირება", "themeCanvas.gallery.wedding.3": "დღესასწაული", "themeCanvas.nav": "ღონისძიების ნიმუშის სექციები", "themeCanvas.nav.invitation": "მოსაწვევი", "themeCanvas.nav.details": "დეტალები", "themeCanvas.nav.moments": "მომენტები", "themeCanvas.open": "გახსენი მოსაწვევი", "themeCanvas.scroll": "გადაახვიე და აღმოაჩინე", "themeCanvas.story": "01 / ისტორია", "themeCanvas.invitation.label": "02 / მოსაწვევი", "themeCanvas.invitation.title": "პირველი მისალმება ამ მომენტისთვის.", "themeCanvas.invitation.description": "ასე მოდის დღესასწაული: დღის პატარა ნაწილი, სანამ ის დაიწყება.", "themeCanvas.celebration": "დღესასწაული", "themeCanvas.celebrateBirthday": "მოდი, ერთად ვიზეიმოთ.", "themeCanvas.celebrateWedding": "შემოგვიერთდი ამ დღეს.", "themeCanvas.when": "როდის", "themeCanvas.at": "{time}-ზე", "themeCanvas.where": "სად", "themeCanvas.birthdayShoes": "ჩაიცვი შენი საყვარელი საცეკვაო ფეხსაცმელი", "themeCanvas.weddingSeeYou": "მოუთმენლად გელით", "themeCanvas.countdown": "უკუთვლა", "themeCanvas.days": "{count} დღე", "themeCanvas.until": "დღესასწაულამდე", "themeCanvas.community": "04 / შენი ადამიანები", "themeCanvas.rsvp": "05 / ადგილი დაიკავე", "themeCanvas.reply": "შენი პასუხის ნახვა", "themeCanvas.replied": "პასუხი ნაჩვენებია", "themeCanvas.replyNote": "რეალურ ღონისძიებაზე ეს პასუხი მასპინძელს გაეგზავნებოდა.", "themeCanvas.previewNote": "ინტერაქტიული მაგალითი · პასუხი არ ინახება", "themeCanvas.cardAria": "{name} თემის წინასწარი ნახვა",
  "template.its": "ეს არის", "template.birthday": "დაბადების დღე!", "template.turning": "უსრულდება {age}", "template.date": "თარიღი", "template.time": "დრო", "template.place": "ადგილი", "template.at": "{time}-ზე", "template.together": "ახალი თავი ერთად",
  "modulePreview.label": "არჩევითი მოდული", "modulePreview.guest": "— სტუმარი {name}-ის ღონისძიებაზე", "themePreview.notFound.title": "თემა ვერ მოიძებნა", "themePreview.notFound.description": "ეს დიზაინი კოლექციაში არ არის.", "themePreview.experience": "ღონისძიების გამოცდილება", "themePreview.design": "დიზაინი", "themePreview.makeYours": "შენებური გახადე", "themePreview.title": "ერთი თემა, შენი ისტორიის მეტი ნაწილი.", "themePreview.description": "აირჩიე დამატებითი ფუნქცია და ნახე, როგორ ერწყმის ამ დიზაინს.", "themePreview.aria": "დამატებითი ღონისძიების მოდულების ნახვა", "themePreview.more": "მეტი დიზაინის ნახვა", "themeExplorer.choose": "აირჩიე დიზაინი", "themeExplorer.title": "ერთი დღესასწაული, შენი სტილის უამრავი გზა.", "themeExplorer.description": "დაიწყე ვიზუალური სამყაროთი, რომელიც მოგწონს. მოსაწვევები და დამატებითი ფუნქციები მას მოერგება.",
  "surprise.phone.made": "ერთი ადამიანისთვის შექმნილი", "surprise.phone.photo": "ორი მეგობარი ზღვისპირა ტერასაზე", "surprise.phone.open": "გახსენი ეს პატარა სამყარო", "surprise.cover.fromTo": "{from}-სგან · {to}-სთვის", "surprise.cover.begin": "დაიწყე სიურპრიზი", "surprise.cover.bottom": "შენთვის შექმნილი პატარა სამყარო", "surprise.message.label": "01 / გულიდან", "surprise.message.title": "გილოცავ დაბადების დღეს, {name}.", "surprise.message.sign": "მთელი სიყვარულით, {name}", "surprise.notes.label": "03 / პატარა ამბები", "surprise.notes.title": "პატარა რამეები, რაც შენში მიყვარს.", "surprise.memories.label": "04 / გახსოვს?", "surprise.memories.title": "დღეები, რომლებსაც ისევ ვუბრუნდები.", "surprise.gallery.label": "05 / ჩვენი ფოტოები", "surprise.gallery.title": "კიდევ მეტი საერთო მომენტი.", "surprise.gallery.description": "სხვადასხვა ადგილი, იგივე საყვარელი ადამიანი.", "surprise.timeline.label": "06 / ჩვენი ისტორია", "surprise.timeline.title": "ნახე, რამდენი გზა გამოვიარეთ.", "surprise.quiz.label": "07 / გახსოვს?", "surprise.quiz.title": "პატარა კითხვა შენთვის.", "surprise.quiz.choose": "აირჩიე პასუხი და მოგონება გაიხსენე.", "surprise.quiz.correct": "გახსოვს! ამ დღეზე დღემდე ვლაპარაკობთ.", "surprise.quiz.wrong": "თითქმის! ჩვენი თავგადასავალი სანაპიროზე დაიწყო.", "surprise.wishes.label": "08 / მომავალი წლისთვის", "surprise.wishes.title": "ჩემი სურვილები შენთვის.", "surprise.music.label": "არჩევითი / ჩვენი სიმღერა", "surprise.music.title": "სიმღერა ამ პატარა სამყაროსთვის.", "surprise.music.description": "მუსიკაც შეიძლება შენი სიურპრიზის ნაწილი გახდეს. ამ მაგალითს ხმა არ ახლავს.",
  "surprise.cake.aria": "დაბადების დღის ტორტი სამი სანთლით", "surprise.cake.candle": "ჩააქრე სანთელი {number}", "surprise.cake.label": "02 / პატარა სურვილი", "surprise.cake.title": "ჩაიფიქრე სურვილი.", "surprise.cake.description": "სამი სანთელი და ერთი დიდი სურვილი. ეს პატარა მომენტი მხოლოდ შენია.", "surprise.cake.made": "სურვილი ჩაფიქრებულია", "surprise.cake.blessing": "ნეტავ ეს წელი შენსავით მშვენიერი იყოს.", "surprise.cake.relight": "თავიდან აანთე", "surprise.cake.tap": "შეეხე თითოეულ სანთელს ჩასაქრობად.", "surprise.cake.blowAll": "ყველა სანთელი ჩააქრე", "surprise.cake.wish": "ჩაიფიქრე სურვილი", "surprise.gift.label": "09 / მხოლოდ შენთვის", "surprise.gift.title": "პატარა რამ შენთვის.", "surprise.gift.description": "კიდევ ერთი რამ მინდა გაჩუქო.", "surprise.gift.wrap": "ისევ შეფუთე", "surprise.gift.open": "გახსენი საჩუქარი", "surprise.letter.label": "10 / კიდევ ერთი რამ", "surprise.letter.title": "ჩემი წერილი შენთვის.", "surprise.letter.description": "ზოგიერთ სიტყვას საკუთარი ადგილი სჭირდება.", "surprise.letter.envelope": "შენთვის, ყოველთვის.", "surprise.letter.close": "დახურე წერილი", "surprise.letter.open": "გახსენი წერილი", "surprise.letter.sign": "სიყვარულით, {name}",
  "surprises.label": "ციფრული სიურპრიზი / 11:11", "surprises.showcase.description": "შეტყობინებაზე მეტი — ფოტოებით, მოგონებებით, სურვილებითა და სიურპრიზებით სავსე პატარა სამყარო, რომელიც ერთ ადამიანს ელის.", "surprises.create": "შექმენი შენი სიურპრიზი", "surprises.openExample": "გახსენი დაბადების დღის მაგალითი", "surprises.launchNote": "შენ მიერ შექმნილი. როცა ეს გამოცდილება ხელმისაწვდომი გახდება, მას ერთი პირადი ბმულით გააზიარებ.", "surprises.flow.label": "როგორ იქმნება", "surprises.flow.title": "ხუთი ნაბიჯი მისთვის შექმნილ პატარა სამყარომდე.", "surprises.flow.0": "აირჩიე შემთხვევა", "surprises.flow.1": "აირჩიე თემა", "surprises.flow.2": "დაამატე მოგონებები", "surprises.flow.3": "დაამატე ინტერაქტიული მომენტები", "surprises.flow.4": "გააზიარე სიურპრიზი", "surprises.config.label": "შექმენი სიურპრიზი · წინასწარი ვერსია", "surprises.config.title": "დაიწყე მისი ისტორიით.", "surprises.config.description": "აირჩიე მიზეზი, დიზაინი და მომენტები. ეს ნიმუში საცდელ შიგთავსს იყენებს და შენს არჩევანს არ ინახავს.", "surprises.occasion.title": "რას აღნიშნავ?", "surprises.occasion.description": "განსაკუთრებულ დღეს თუ უბრალოდ განსაკუთრებულ ადამიანს.", "surprises.occasion.aria": "აირჩიე სიურპრიზის შემთხვევა", "surprises.theme.title": "შეურჩიე იერი.", "surprises.theme.description": "ეს თემები მთელ 11:11-ში გამოიყენება.", "surprises.theme.aria": "აირჩიე სიურპრიზის თემა", "surprises.modules.title": "დაამატე ის, რაც მას ჰგავს.", "surprises.modules.description": "აირჩიე მისი სიურპრიზის შესაბამისი მომენტები.", "surprises.modules.aria": "აირჩიე დამატებითი მომენტები", "surprises.preview.label": "შენი არჩევანის წინასწარი ნახვა", "surprises.preview.count": "არჩეულია {count} დამატებითი მომენტი", "surprises.preview.action": "დაბადების დღის მაგალითის ნახვა", "surprises.preview.note": "სრული ინტერაქტიული მაგალითი დაბადების დღის სიურპრიზია. აქ გაკეთებული არჩევანი მხოლოდ ამ ბრაუზერის წინასწარ ხედვას ეხება.", "surprises.share.label": "ბოლო შტრიხი", "surprises.share.title": "ერთი ლამაზი ბმული. ერთი ადამიანი, ვისთვისაც შექმენი.", "surprises.share.description": "როცა შექმნა და გაზიარება ხელმისაწვდომი გახდება, მას შენი სიურპრიზის გახსნა ნებისმიერი ადგილიდან შეეძლება.", "surprises.share.note": "ბმული მხოლოდ მაგალითია · ამ ნიმუშში ბმული არ იქმნება",
  "surprises.demo.back": "ციფრული სიურპრიზი", "surprises.demo.label": "დაბადების დღის ინტერაქტიული მაგალითი · სანიმუშო შიგთავსი", "surprises.demo.eyebrow": "იგივე ისტორია, სხვა იერი", "surprises.demo.title": "შეცვალე თემა. შეინარჩუნე გრძნობა.", "surprises.demo.description": "ქვემოთ მოცემული ყოველი ნაწილი შენ მიერ არჩეულ თემას მიჰყვება. ერთი ადამიანისთვის შექმნილ სიურპრიზს ღონისძიების ადგილი ან მონაწილეობის დადასტურება არ სჭირდება.", "surprises.demo.aria": "დაბადების დღის სიურპრიზის თემები", "surprises.demo.end": "წარმოიდგენდი მსგავსს შენთვის ძვირფასი ადამიანისთვის?",
  "surprises.specialPerson": "განსაკუთრებული ადამიანისთვის",
  "loader.status": "ემოციები იტვირთება. გთხოვ, მოიცადე.", "loader.message": "ემოციები იტვირთება...", "loader.wait": "გთხოვ, მოიცადე...",
  "meta.title": "11:11 — აქციე მომენტი განსაკუთრებულად", "meta.description": "11:11 — სივრცე მომენტებისთვის, რომლებიც მნიშვნელოვანია.",
  "moodboard.language": "დიზაინის ენა", "moodboard.type.title": "შრიფტი თავისი ხასიათით", "moodboard.type.description": "ასოები განწყობას დღესასწაულამდე ქმნიან.", "moodboard.shared": "კარგი დღეები ერთად უნდა გავიზიაროთ", "moodboard.details.title": "პატარა დეტალები", "moodboard.details.description": "ფერი, ორნამენტი და პატარა ნიშნები იმავე განწყობას ინარჩუნებს.", "moodboard.palette": "ფერების პალიტრა", "moodboard.palette.title": "ოთხი ფერი. ერთი განწყობა.", "moodboard.pattern": "ნიშნები და ორნამენტი", "moodboard.occasion": "დღესასწაული", "moodboard.support.title": "მოსაწვევის მიღმა", "moodboard.support.description": "რამდენიმე ვიზუალური ელემენტი იმ ღონისძიების სამყაროდან, რომელსაც ეს დიზაინი შექმნიდა.", "moodboard.saveDate": "დაიმახსოვრე თარიღი", "moodboard.details": "ღონისძიების დეტალები", "moodboard.note": "პატარა წერილი", "moodboard.made": "11:11 · შექმნილია მომენტისთვის", "moodboard.disclaimer": "ეს დიზაინის ნიმუშებია. ინტერაქტიული ფუნქციები მომავალში შექმნილ ღონისძიებას ეკუთვნის.",
  "surprises.home.index": "03 / ციფრული სიურპრიზი", "surprises.hero.question": "შორს ხარ და პირადად ვერ ხვდებით?", "surprises.hero.emphasis": "შეუქმენი რამე, რაც დაამახსოვრდება.", "surprises.home.description": "ფოტოები, მოგონებები, სურვილები და პატარა ინტერაქტიული მომენტები. ყველაფერი ერთ ადამიანს ელის, სადაც არ უნდა იყოს.", "surprises.home.action": "ციფრული სიურპრიზის ნახვა", "surprises.home.note": "შეტყობინებაზე მეტი. მისთვის შექმნილი პატარა სამყარო.",
  "friendship.back": "დაბადების დღის მოდულები", "friendship.hero.label": "არჩევითი ღონისძიების მოდული / 11:11", "friendship.hero.title": "მეგობრობის დღიური — შენი მომენტისთვის.", "friendship.hero.description": "დაუსვი კითხვები, რომლებზეც პასუხი მხოლოდ შენს ადამიანებს აქვთ. დაამატე დღიური დაბადების დღის ღონისძიებას და მის დიზაინს მოარგე.", "friendship.hero.action": "დაბადების დღის თემების ნახვა", "friendship.looks.label": "ერთი ფუნქცია, მრავალი სახე", "friendship.looks.title": "ისტორია შენია. სტილი იცვლება.", "friendship.looks.description": "მეგობრობის დღიური ღონისძიების ნაწილია. აქ ერთი და იგივე ნიმუში დაბადების დღის ორ თემაშია.", "friendship.questions.label": "კარგი კითხვები", "friendship.questions.title": "პატარა კითხვა ბევრ რამეს ხსნის", "friendship.questions.description": "ექვსი მაგალითი მეგობრებს ახსენებს მომენტებს, რომლებიც ყველაზე კარგად ახსოვთ.", "friendship.responses.label": "სანიმუშო პასუხები", "friendship.responses.title": "შესანახი პასუხები", "friendship.responses.description": "იმ ისტორიების მაგალითი, რომლებიც ღონისძიების ნაწილად შეიძლება იქცეს.",
  "corporate.hero.label": "კორპორატიული / 11:11", "corporate.hero.title": "კარგი საქმე კარგ შეკრებას იმსახურებს.", "corporate.hero.description": "შექმენი კომპანიის ღონისძიება, რომელიც პირადი, გააზრებული და დასამახსოვრებელია.", "corporate.explore": "მოსაწვევების სტილების ნახვა", "corporate.art.title": "შეკრება", "corporate.art.caption": "ადამიანები · მიზანი · შეხვედრის მიზეზი", "corporate.section.label": "ცოტა მეტი ადამიანურობა", "corporate.section.title": "ყველა მიზეზისთვის, რომელიც ადამიანებს აერთიანებს", "corporate.section.description": "მოქნილ ციფრულ სივრცეში ეტევა მოსაწვევი, დეტალები და შემდგომი მოგონებები.", "corporate.occasion.0": "კომპანიის დღესასწაულები", "corporate.occasion.1": "პროდუქტის პრეზენტაციები", "corporate.occasion.2": "კერძო ვახშმები", "corporate.occasion.3": "გუნდის ღონისძიებები", "corporate.occasion.4": "კონფერენციები", "corporate.occasion.5": "ნეთვორქინგის საღამოები", "corporate.note.title": "შემდეგი კოლექცია ფორმას იძენს.", "corporate.note.description": "კორპორატიული თემები მალე გამოჩნდება. მოსაწვევის, გალერეის, სტუმრის შეტყობინებისა და ღონისძიების დეტალების მოდულები შენს შემთხვევასაც მოერგება.", "corporate.cta.title": "შეკრება დასამახსოვრებელი გახადე.", "corporate.cta.description": "სანამ კორპორატიული თემები მზადდება, გაეცანი უკვე არსებულ დიზაინებს.", "corporate.cta.action": "მოსაწვევების დათვალიერება",
  "other.hero.label": "სხვა დღესასწაულები / 11:11", "other.hero.title": "ყოველ მიზეზს თავისი ჯადოსნობა აქვს.", "other.hero.description": "დიდი სიურპრიზიდან მშვიდ და მნიშვნელოვან მომენტამდე — ყველასთვის არის ადგილი.", "other.chooser.label": "აირჩიე შემთხვევა", "other.chooser.title": "რას ვზეიმობთ?", "other.chooser.description": "ეს 11:11-ის სამყაროში შემომავალი ახალი დღესასწაულების პირველი ხედვაა.", "other.chooser.aria": "სხვა დღესასწაულების ტიპები", "other.preview.aria": "დღესასწაულის ტიპის წინასწარი ნახვა", "other.stage.label": "11:11 / შემთხვევის წინასწარი ნახვა", "other.stage.tag": "თემები მოგვიანებით დაემატება ✧", "other.cta.title": "შენი შემთხვევა, შენი გზა.", "other.cta.description": "კიდევ მეტი დიზაინი მალე გამოჩნდება. მანამდე ნახე, რისი შექმნა შეუძლია 11:11-ს.",
});

Object.assign(captions.en, {
  "themeCanvas.aria": "{name} invitation design", "themeCanvas.birthdayInvite": "A BIRTHDAY INVITATION", "themeCanvas.weddingInvite": "A WEDDING INVITATION", "themeCanvas.gallery.label": "03 / MOMENTS", "themeCanvas.gallery.birthday.0": "The dance floor", "themeCanvas.gallery.birthday.1": "Make a wish", "themeCanvas.gallery.birthday.2": "Our people", "themeCanvas.gallery.birthday.3": "One more toast", "themeCanvas.gallery.wedding.0": "Together", "themeCanvas.gallery.wedding.1": "The table", "themeCanvas.gallery.wedding.2": "The promise", "themeCanvas.gallery.wedding.3": "The celebration", "themeCanvas.nav": "Event preview sections", "themeCanvas.nav.invitation": "Invitation", "themeCanvas.nav.details": "Details", "themeCanvas.nav.moments": "Moments", "themeCanvas.open": "Open the invitation", "themeCanvas.scroll": "SCROLL TO EXPLORE", "themeCanvas.story": "01 / THE STORY", "themeCanvas.invitation.label": "02 / THE INVITATION", "themeCanvas.invitation.title": "A first hello, made for this moment.", "themeCanvas.invitation.description": "This is how the celebration arrives: a little piece of the day, before the day begins.", "themeCanvas.celebration": "THE CELEBRATION", "themeCanvas.celebrateBirthday": "Come celebrate with us.", "themeCanvas.celebrateWedding": "Join us for the day.", "themeCanvas.when": "WHEN", "themeCanvas.at": "At {time}", "themeCanvas.where": "WHERE", "themeCanvas.birthdayShoes": "Bring your favorite dancing shoes", "themeCanvas.weddingSeeYou": "We can’t wait to see you there", "themeCanvas.countdown": "COUNTING DOWN", "themeCanvas.days": "{count} days", "themeCanvas.until": "Until the celebration", "themeCanvas.community": "04 / YOUR PEOPLE", "themeCanvas.rsvp": "05 / SAVE YOUR PLACE", "themeCanvas.reply": "Preview your reply", "themeCanvas.replied": "Reply previewed", "themeCanvas.replyNote": "A real event page would send this response to the host.", "themeCanvas.previewNote": "Interactive example · no response is saved", "themeCanvas.cardAria": "Preview {name} theme",
  "template.its": "IT’S", "template.birthday": "Birthday!", "template.turning": "Turning {age}", "template.date": "DATE", "template.time": "TIME", "template.place": "PLACE", "template.at": "at {time}", "template.together": "A new chapter, together",
  "modulePreview.label": "OPTIONAL MODULE", "modulePreview.guest": "— a guest at {name}’s event", "themePreview.notFound.title": "Theme not found", "themePreview.notFound.description": "That design isn’t in the collection.", "themePreview.experience": "EVENT EXPERIENCE", "themePreview.design": "DESIGN", "themePreview.makeYours": "MAKE IT YOURS", "themePreview.title": "One theme, more of your story.", "themePreview.description": "Choose an optional feature to see how it belongs inside this design.", "themePreview.aria": "Preview optional event modules", "themePreview.more": "Explore more designs", "themeExplorer.choose": "CHOOSE YOUR DESIGN", "themeExplorer.title": "One celebration. So many ways to make it yours.", "themeExplorer.description": "Start with a visual world you love. Invitations and optional features follow its look.",
  "surprise.phone.made": "MADE FOR ONE PERSON", "surprise.phone.photo": "Two friends on a coastal terrace", "surprise.phone.open": "Open this little world", "surprise.cover.fromTo": "FROM {from} · TO {to}", "surprise.cover.begin": "Begin the surprise", "surprise.cover.bottom": "A LITTLE WORLD MADE FOR YOU", "surprise.message.label": "01 / FROM THE HEART", "surprise.message.title": "Happy birthday, {name}.", "surprise.message.sign": "With all my love, {name}", "surprise.notes.label": "03 / THE LITTLE THINGS", "surprise.notes.title": "The little things I love about you.", "surprise.memories.label": "04 / REMEMBER WHEN", "surprise.memories.title": "The days I keep coming back to.", "surprise.gallery.label": "05 / OUR CAMERA ROLL", "surprise.gallery.title": "More moments together.", "surprise.gallery.description": "Different places, same favorite person.", "surprise.timeline.label": "06 / OUR STORY", "surprise.timeline.title": "Look how far we’ve come.", "surprise.quiz.label": "07 / DO YOU REMEMBER?", "surprise.quiz.title": "A little question for you.", "surprise.quiz.choose": "Choose an answer to reveal the memory.", "surprise.quiz.correct": "You remember! We still talk about that day.", "surprise.quiz.wrong": "Not quite. The coast was where the adventure began.", "surprise.wishes.label": "08 / FOR THE YEAR AHEAD", "surprise.wishes.title": "My wishes for you.", "surprise.music.label": "OPTIONAL / OUR SONG", "surprise.music.title": "A song for this little world.", "surprise.music.description": "Music can be part of your surprise. This example has no audio attached.",
  "surprise.cake.aria": "Birthday cake with three candles", "surprise.cake.candle": "Blow out candle {number}", "surprise.cake.label": "02 / A LITTLE WISH", "surprise.cake.title": "Make a wish.", "surprise.cake.description": "Three candles, one big wish. This little moment is all yours.", "surprise.cake.made": "Wish made", "surprise.cake.blessing": "May this year be as wonderful as you are.", "surprise.cake.relight": "Light them again", "surprise.cake.tap": "Tap each candle to blow it out.", "surprise.cake.blowAll": "Blow them all out", "surprise.cake.wish": "Make a wish", "surprise.gift.label": "09 / JUST FOR YOU", "surprise.gift.title": "A little something for you.", "surprise.gift.description": "There is one more thing I wanted to give you.", "surprise.gift.wrap": "Wrap it again", "surprise.gift.open": "Open your gift", "surprise.letter.label": "10 / ONE LAST THING", "surprise.letter.title": "A letter from me to you.", "surprise.letter.description": "Some words deserve a place of their own.", "surprise.letter.envelope": "For you, always.", "surprise.letter.close": "Close the letter", "surprise.letter.open": "Open the letter", "surprise.letter.sign": "With love, {name}",
  "surprises.label": "DIGITAL SURPRISE / 11:11", "surprises.showcase.description": "More than a message. A whole little world of photos, memories, wishes, and surprises, made for one person to open.", "surprises.create": "Create your surprise", "surprises.openExample": "Open the Birthday example", "surprises.launchNote": "Made by you. Shared through one private link when this experience is ready to launch.", "surprises.flow.label": "HOW IT COMES TOGETHER", "surprises.flow.title": "Five steps to a little world made for them.", "surprises.flow.0": "Choose an occasion", "surprises.flow.1": "Pick a theme", "surprises.flow.2": "Add your memories", "surprises.flow.3": "Add interactive moments", "surprises.flow.4": "Share the surprise", "surprises.config.label": "CREATE YOUR SURPRISE · FRONTEND PREVIEW", "surprises.config.title": "Start with their story.", "surprises.config.description": "Choose a reason, a look, and the moments you want to include. This preview uses sample content and does not save your choices.", "surprises.occasion.title": "What are you celebrating?", "surprises.occasion.description": "A special day, or simply a special person.", "surprises.occasion.aria": "Choose a surprise occasion", "surprises.theme.title": "Give it a look.", "surprises.theme.description": "These are the same themes used across 11:11.", "surprises.theme.aria": "Choose a surprise theme", "surprises.modules.title": "Add what feels like them.", "surprises.modules.description": "Pick the moments that belong in their surprise.", "surprises.modules.aria": "Choose optional surprise moments", "surprises.preview.label": "A PREVIEW OF YOUR DIRECTION", "surprises.preview.count": "{count} optional moments selected", "surprises.preview.action": "Preview the Birthday example", "surprises.preview.note": "The full interactive example is a Birthday Surprise. Your choices here are local to this browser preview.", "surprises.share.label": "THE FINISHING TOUCH", "surprises.share.title": "One beautiful link. One person you made it for.", "surprises.share.description": "When creation and sharing are available, your surprise will be ready for them to open wherever they are.", "surprises.share.note": "Illustrative link only · no link is created in this demo",
  "surprises.demo.back": "Digital Surprise", "surprises.demo.label": "INTERACTIVE BIRTHDAY EXAMPLE · SAMPLE CONTENT", "surprises.demo.eyebrow": "SAME STORY, DIFFERENT LOOK", "surprises.demo.title": "Switch the theme. Keep the feeling.", "surprises.demo.description": "Each section below follows the theme you choose. No event venue or RSVP is needed for a surprise made for one person.", "surprises.demo.aria": "Preview birthday surprise themes", "surprises.demo.end": "Want to imagine one for your person?",
  "surprises.specialPerson": "For someone special",
  "loader.status": "Feelings are loading. Please wait.", "loader.message": "Feelings are loading....", "loader.wait": "Please Wait...",
  "meta.title": "11:11 — Make it count", "meta.description": "11:11 — make room for the moments that count.",
  "moodboard.language": "THE DESIGN LANGUAGE", "moodboard.type.title": "Type with a point of view", "moodboard.type.description": "The lettering sets the mood before the celebration begins.", "moodboard.shared": "GOOD DAYS ARE MEANT TO BE SHARED", "moodboard.details.title": "The little details", "moodboard.details.description": "Color, pattern, and small marks carry the same feeling throughout.", "moodboard.palette": "THE PALETTE", "moodboard.palette.title": "Four colors. One feeling.", "moodboard.pattern": "MARKS & PATTERN", "moodboard.occasion": "THE OCCASION", "moodboard.support.title": "Beyond the invitation", "moodboard.support.description": "A few visual pieces from the wider event world this design could create.", "moodboard.saveDate": "SAVE THE DATE", "moodboard.details": "EVENT DETAILS", "moodboard.note": "A LITTLE NOTE", "moodboard.made": "11:11 · MADE FOR THE MOMENT", "moodboard.disclaimer": "These are design samples. Interactive event features belong to the future created experience.",
  "surprises.home.index": "03 / DIGITAL SURPRISE", "surprises.hero.question": "Can’t be there in person?", "surprises.hero.emphasis": "Make them something they’ll remember.", "surprises.home.description": "Photos, memories, wishes, and interactive little moments. All made for one person to open, wherever they are.", "surprises.home.action": "Explore Digital Surprise", "surprises.home.note": "More than a message. A whole little world made for them.",
  "friendship.back": "Birthday modules", "friendship.hero.label": "OPTIONAL EVENT MODULE / 11:11", "friendship.hero.title": "Friendship Diary, made for your moment.", "friendship.hero.description": "Ask the questions only your people could answer. Add the diary to a Birthday event and let its look follow the design you choose.", "friendship.hero.action": "Explore Birthday themes", "friendship.looks.label": "ONE FEATURE, MANY LOOKS", "friendship.looks.title": "The story stays yours. The style changes.", "friendship.looks.description": "A Friendship Diary is part of an event, not a separate app. Here is the same preview in two Birthday themes.", "friendship.questions.label": "GOOD QUESTIONS", "friendship.questions.title": "A little prompt goes a long way", "friendship.questions.description": "Six example questions help friends share the moments they remember best.", "friendship.responses.label": "MOCK RESPONSES", "friendship.responses.title": "Answers worth keeping", "friendship.responses.description": "A preview of the kind of stories that can live inside an event.",
  "corporate.hero.label": "CORPORATE / 11:11", "corporate.hero.title": "Good work deserves a good gathering.", "corporate.hero.description": "Make a company event feel personal, considered, and worth remembering.", "corporate.explore": "Explore invitation styles", "corporate.art.title": "THE GATHERING", "corporate.art.caption": "people · purpose · a reason to meet", "corporate.section.label": "A LITTLE MORE HUMAN", "corporate.section.title": "For every reason to bring people together", "corporate.section.description": "A flexible digital event space can carry the invitation, the details, and the memories that follow.", "corporate.occasion.0": "Company celebrations", "corporate.occasion.1": "Product launches", "corporate.occasion.2": "Private dinners", "corporate.occasion.3": "Team events", "corporate.occasion.4": "Conferences", "corporate.occasion.5": "Networking nights", "corporate.note.title": "The next collection is taking shape.", "corporate.note.description": "Corporate-specific themes are on the way. The same invitation, gallery, guest message, and event-detail modules can adapt to your occasion.", "corporate.cta.title": "Make the gathering memorable.", "corporate.cta.description": "Explore the design language already available while corporate themes are in progress.", "corporate.cta.action": "Browse invitations",
  "other.hero.label": "OTHER CELEBRATIONS / 11:11", "other.hero.title": "Every reason has its own magic.", "other.hero.description": "From the big surprises to the quiet milestones, there’s room to make it yours.", "other.chooser.label": "CHOOSE AN OCCASION", "other.chooser.title": "What are we celebrating?", "other.chooser.description": "These are the first looks at more celebrations joining the 11:11 world.", "other.chooser.aria": "Other celebration types", "other.preview.aria": "Preview a celebration type", "other.stage.label": "11:11 / OCCASION PREVIEW", "other.stage.tag": "Themes coming later ✧", "other.cta.title": "Your occasion, your way.", "other.cta.description": "More designs are on the way. Start by exploring what 11:11 can already create.",
});

const showcaseCopy = {
  ka: {
    birthdayPrompts: [["საყვარელი მოგონება", "ის, რომელზეც დღემდე ლაპარაკობთ."], ["ყველაზე სასაცილო მომენტი", "ისტორია, რომელიც არასდროს ძველდება."], ["პირველი შთაბეჭდილება", "როგორ დაიწყო თქვენი ამბავი."], ["მომავლისთვის", "წერილი, რომელსაც ერთ დღეს გახსნი."]],
    birthdayGames: [["ვინ მიცნობს ყველაზე კარგად?", "პატარა მეგობრული შეჯიბრი."], ["დაბადების დღის ვიქტორინა", "კითხვები, რომლებზეც პასუხი მხოლოდ შენმა ადამიანებმა იციან."], ["ეს თუ ის", "სწრაფი არჩევანი, ძლიერი აზრები."], ["გამოიცანი მოგონება", "ვის ახსოვს, რა მოხდა?"]],
    weddingFeatures: [["ციფრული მოსაწვევი", "ლამაზი პირველი მისალმება."], ["მონაწილეობის დადასტურება", "პასუხის მარტივი გზა."], ["სტუმრების წიგნი", "თბილი სიტყვები შესანახად."], ["წყვილის ისტორია", "თქვენი გზა თქვენი სიტყვებით."], ["ღონისძიების განრიგი", "ყოველ მომენტს თავისი ადგილი."], ["მდებარეობა", "დაეხმარე ყველას გზის პოვნაში."], ["ფოტომოგონებები", "ეს დღე ყველა ხედვით."]],
    friendshipQuestions: [["როგორ გავიცანით ერთმანეთი?", "ყველა მეგობრობას თავისი პირველი გვერდი აქვს."], ["შენი პირველი შთაბეჭდილება ჩემზე", "გულწრფელად მითხარი. ახლა ამაზე სიცილი შეგვიძლია."], ["ჩემთან დაკავშირებული საყვარელი მოგონება", "დიდი თუ პატარა, ყველაფერი მნიშვნელოვანია."], ["ყველაზე სასაცილო საერთო მომენტი", "ის, რომელსაც დღემდე ვიხსენებთ."], ["აღმწერე სამი სიტყვით", "სამი სიტყვის შერჩევა არც ისე ადვილია."], ["შეტყობინება მომავლისთვის", "რაღაც, რასაც მოგვიანებით დაუბრუნდები."]],
  },
  en: {
    birthdayPrompts: [["Favorite memory", "The one you still talk about."], ["Funniest moment", "The story that never gets old."], ["First impression", "How the story began."], ["For the future", "A note to open one day."]],
    birthdayGames: [["Who Knows Me Best?", "A little friendly competition."], ["Birthday Quiz", "Questions only your people know."], ["This or That", "Quick choices, big opinions."], ["Guess the Memory", "Who remembers what happened?"]],
    weddingFeatures: [["Digital invitation", "A beautiful first hello."], ["RSVP", "A simple way to hear back."], ["Guest book", "Kind words to keep."], ["Couple story", "Your journey, in your words."], ["Event schedule", "Every moment in its place."], ["Location", "Help everyone find their way."], ["Photo memories", "The day through every lens."]],
    friendshipQuestions: [["How did we meet?", "Every friendship has a first page."], ["Your first impression of me", "Be honest. We can laugh about it now."], ["Favorite memory with me", "Big or small, it all counts."], ["Funniest moment together", "The one we still bring up."], ["Describe me in three words", "Three is harder than it sounds."], ["A message for the future", "Something to return to later."]],
  },
};

for (const language of languages) {
  for (const [group, entries] of Object.entries(showcaseCopy[language])) {
    entries.forEach(([title, detail], index) => {
      captions[language][`showcase.${group}.${index}.title`] = title;
      captions[language][`showcase.${group}.${index}.detail`] = detail;
    });
  }
}

const moduleCatalog = [
  ["invitation", "მოსაწვევი", "ლამაზი პირველი მისალმება.", "Invitation", "A beautiful first hello."],
  ["countdown", "უკუთვლა", "მოლოდინი უფრო საინტერესო გახადე.", "Countdown", "Let the excitement build."],
  ["gallery", "ფოტოგალერეა", "ეს დღე ყველა ხედვით.", "Photo Gallery", "The day through every lens."],
  ["rsvp", "მონაწილეობის დადასტურება", "პასუხის მარტივი გზა.", "RSVP", "A simple way to hear back."],
  ["friendship-diary", "მეგობრობის დღიური", "კითხვები, რომლებზეც პასუხი მხოლოდ მეგობრებმა იციან.", "Friendship Diary", "Questions only your friends could answer."],
  ["guest-book", "სტუმრების წიგნი", "თბილი სიტყვები შესანახად.", "Guest Book", "Kind words to keep close."],
  ["memories", "მოგონებები", "ისტორიები, რომლებსაც ისევ დაუბრუნდები.", "Memories", "Stories worth returning to."],
  ["quiz", "ვიქტორინა", "მხიარული კითხვები შენი ადამიანებისთვის.", "Quiz", "Playful questions for your people."],
  ["games", "თამაშები", "პატარა მხიარულება მომენტებს შორის.", "Games", "A little fun between moments."],
  ["guest-messages", "სტუმრების შეტყობინებები", "წერილები მნიშვნელოვანი ადამიანებისგან.", "Guest Messages", "Notes from the people who matter."],
  ["event-details", "ღონისძიების დეტალები", "ყველაფერი, რაც სტუმრებმა უნდა იცოდნენ.", "Event Details", "Everything guests need to know."],
  ["main-message", "მთავარი წერილი", "სიტყვები, რომლებიც ყველაზე მეტად გინდა უთხრა.", "Main Message", "The words you most want them to hear."],
  ["cake", "ინტერაქტიული ტორტი", "დაბადების დღის სურვილი, რომელსაც თვითონ ჩაიფიქრებს.", "Interactive Cake", "A birthday wish they can make themselves."],
  ["love-notes", "პირადი წერილები", "ყველა პატარა რამ, რაც მას განსაკუთრებულს ხდის.", "Personal Notes", "All the little things that make them special."],
  ["wishes", "სურვილები", "იმედი ყველაფრისთვის, რაც წინ არის.", "Wishes", "Hopes for all that is still to come."],
  ["gift", "ვირტუალური საჩუქარი", "პატარა სიურპრიზი მხოლოდ მისთვის.", "Virtual Gift", "A little reveal saved just for them."],
  ["letter", "ბოლო წერილი", "კიდევ ერთი გულწრფელი წერილი.", "Final Letter", "One last note from the heart."],
  ["timeline", "ჩვენი ისტორია", "მომენტები, რომლებმაც აქამდე მოგიყვანათ.", "Our Story", "The moments that brought you here."],
  ["music", "მუსიკა", "ადგილი თქვენი სიმღერისთვის.", "Music", "A place for your song, when you have one."],
];
const occasionCatalog = [
  ["birthday", "დაბადების დღე", "კიდევ ერთი წელი შენთან ერთად.", "ადამიანისთვის, რომლის დღე უბრალოდ შეტყობინებაზე მეტს იმსახურებს.", "Birthday", "Another year of you.", "For the person whose day deserves more than a text."],
  ["friendship", "მეგობრობა", "ჩემი საყვარელი ადამიანისთვის.", "თქვენი ხუმრობები და საერთო ისტორიები ერთ სივრცეში.", "Friendship", "For my favorite person.", "All your inside jokes and shared stories in one place."],
  ["romantic", "რომანტიკა", "პატარა სამყარო ჩვენთვის.", "რაღაც ნაზი, რასაც ერთმანეთის მონატრებისას გახსნით.", "Romantic", "A little world for us.", "Something tender to open whenever you miss each other."],
  ["anniversary", "წლისთავი", "კიდევ ერთი თავი ერთად.", "გაიხსენეთ ყველაფერი, რაც ერთად გაიარეთ.", "Anniversary", "Another chapter together.", "A way to revisit everything you have become together."],
  ["graduation", "კურსდამთავრება", "ნახე, რამდენს მიაღწიე.", "შრომის, გამბედაობისა და გვერდით მდგომი ადამიანების ზეიმი.", "Graduation", "Look how far you came.", "A celebration of the work, courage, and people behind it."],
  ["just-because", "უმიზეზოდ", "დღეს ამას იმსახურებ.", "ადამიანის გახარებას განსაკუთრებული მიზეზი არ სჭირდება.", "Just Because", "You deserve this today.", "No occasion needed to make someone feel seen."],
];
for (const language of languages) {
  for (const [id, kaTitle, kaDescription, enTitle, enDescription] of moduleCatalog) {
    const values = [kaTitle, kaDescription, enTitle, enDescription];
    const offset = languages.indexOf(language) * 2;
    captions[language][`modules.${id}.title`] = values[offset];
    captions[language][`modules.${id}.description`] = values[offset + 1];
  }
  for (const [id, ...values] of occasionCatalog) {
    const [label, headline, note] = values.slice(languages.indexOf(language) * 3, languages.indexOf(language) * 3 + 3);
    captions[language][`occasions.${id}.label`] = label;
    captions[language][`occasions.${id}.headline`] = headline;
    captions[language][`occasions.${id}.note`] = note;
  }
}

Object.assign(captions.ka, {
  "appearance.dark": "მუქი რეჟიმი", "appearance.light": "ღია რეჟიმი",
  "appearance.switchDark": "მუქ რეჟიმზე გადართვა", "appearance.switchLight": "ღია რეჟიმზე გადართვა",
});
Object.assign(captions.en, {
  "appearance.dark": "Dark mode", "appearance.light": "Light mode",
  "appearance.switchDark": "Switch to dark mode", "appearance.switchLight": "Switch to light mode",
});

// Public product demos share the existing language system.
const productCopy = {
  en: {
    "home.projects.description": "Digital invitations and personal surprises. Choose an occasion, explore a style, and see what your people will open.",
    "home.possibilities.description": "An image says when and where. An 11:11 page can bring people into the moment: invite them before, play together during, and return to the memories after.",
    "home.final.description": "Choose your moment → find your style → make it personal → preview. Explore the demos while we prepare creation and private sharing.",
    "home.interactive.description": "A few thoughtful extras, chosen for your occasion. Start with what matters; add only what makes it more personal.",
    "product.demo.label": "11:11 / GUEST DEMO",
    "product.demo.title": "Beyond the invitation.",
    "product.demo.description": "Open a sample experience with the details, memories, and a reply. No account needed.",
    "product.demo.action": "See the guest experience",
    "product.demo.notice": "Sample guest experience. Replies are a local demo and are not sent or saved. Template unlocking and private event links are coming later.",
    "product.rsvp.question": "Will you be there?",
    "product.rsvp.going": "I’ll be there",
    "product.rsvp.declined": "I can’t make it",
    "product.rsvp.plusOne": "I’m bringing one guest",
    "product.rsvp.submit": "Preview my reply",
    "product.rsvp.going.confirmation": "Your sample reply: attending · {count} seat(s).",
    "product.rsvp.declined.confirmation": "Your sample reply: unable to attend. You can still enjoy the memories.",
    "product.rsvp.edit": "Change my reply",
    "product.rsvp.demo": "Demo only. Nothing is sent to an organizer or saved. This sample invitation allows one extra guest.",
    "product.personalize.title": "Make it personal",
    "product.personalize.description": "Just a name and a few words. Leave these empty to try the sample.",
    "product.personalize.recipientName": "For",
    "product.personalize.creatorName": "From",
    "product.personalize.message": "Your personal message",
    "product.personalize.note": "Preview only. Your text stays in this browser’s navigation, not in the link. Photos and stories below are sample content.",
    "product.surprise.birthday.title": "Happy birthday, {name}!",
    "product.surprise.letter": "Dear {name},\n\n{message}\n\nWith love,\n{from}",
    "surprises.config.description": "Try a theme, add your words, and choose a few little extras. This is a preview; publishing and contributions are coming later.",
    "surprises.preview.action": "Preview the surprise",
    "surprises.preview.note": "Your selected occasion, theme, and moments in one preview. No private link is created yet.",
    "surprises.demo.label": "Interactive surprise demo · sample content",
    "surprises.demo.aria": "Surprise themes",
    "surprises.demo.description": "Open, explore, and try the interactions. Photos and stories are samples; replies and changes are not saved.",
  },
  ka: {
    "home.projects.description": "ციფრული მოსაწვევები და პირადი სიურპრიზები. აირჩიე მომენტი, აღმოაჩინე სტილი და ნახე, რას გახსნიან შენი ადამიანები.",
    "home.possibilities.description": "სურათი გვეუბნება, როდის და სად. 11:11-ის გვერდი კი მომენტის ნაწილად გვაქცევს: მანამდე — მოწვევა, დღესასწაულზე — ერთად გართობა, შემდეგ — მოგონებები.",
    "home.final.description": "აირჩიე მომენტი → იპოვე სტილი → დაამატე შენი სიტყვები → ნახე წინასწარ. სცადე დემო, სანამ შექმნასა და პირად გაზიარებას ვამზადებთ.",
    "home.interactive.description": "შენი მომენტისთვის შერჩეული რამდენიმე განსაკუთრებული დეტალი. დაიწყე მთავარით და დაამატე მხოლოდ ის, რაც უფრო პირადს გახდის.",
    "product.demo.label": "11:11 / სტუმრის დემო",
    "product.demo.title": "მოსაწვევზე მეტი.",
    "product.demo.description": "გახსენი გამოცდილების ნიმუში დეტალებით, მოგონებებითა და პასუხის შესაძლებლობით. ანგარიში არ გჭირდება.",
    "product.demo.action": "ნახე სტუმრის გამოცდილება",
    "product.demo.notice": "სტუმრის გამოცდილების ნიმუში. პასუხები მხოლოდ დემოა — არ იგზავნება და არ ინახება. შაბლონის გახსნა და პირადი ბმულები მოგვიანებით დაემატება.",
    "product.rsvp.question": "შემოგვიერთდები?",
    "product.rsvp.going": "მოვალ",
    "product.rsvp.declined": "ვერ მოვალ",
    "product.rsvp.plusOne": "ერთ სტუმართან ერთად მოვალ",
    "product.rsvp.submit": "პასუხის წინასწარი ნახვა",
    "product.rsvp.going.confirmation": "შენი საცდელი პასუხი: მოვდივარ · {count} ადგილი.",
    "product.rsvp.declined.confirmation": "შენი საცდელი პასუხი: ვერ მოვალ. მოგონებების ნახვა მაინც შეგიძლია.",
    "product.rsvp.edit": "პასუხის შეცვლა",
    "product.rsvp.demo": "მხოლოდ დემო. ორგანიზატორს არაფერი ეგზავნება და არაფერი ინახება. ეს ნიმუში ერთი დამატებითი სტუმრის მოყვანას ითვალისწინებს.",
    "product.personalize.title": "დაამატე შენი სიტყვები",
    "product.personalize.description": "მხოლოდ სახელი და რამდენიმე სიტყვა. ნიმუშის სანახავად დატოვე ცარიელი.",
    "product.personalize.recipientName": "ვისთვის",
    "product.personalize.creatorName": "ვისგან",
    "product.personalize.message": "შენი პირადი შეტყობინება",
    "product.personalize.note": "მხოლოდ წინასწარი ნახვა. შენი ტექსტი ბრაუზერის ნავიგაციაში რჩება და ბმულში არ ხვდება. ფოტოები და ისტორიები ნიმუშებია.",
    "product.surprise.birthday.title": "გილოცავ დაბადების დღეს, {name}!",
    "product.surprise.letter": "ძვირფასო {name},\n\n{message}\n\nსიყვარულით,\n{from}",
    "surprises.config.description": "სცადე თემა, დაამატე შენი სიტყვები და აირჩიე რამდენიმე განსაკუთრებული დეტალი. ეს წინასწარი ნახვაა; გამოქვეყნება და მეგობრების მონაწილეობა მოგვიანებით დაემატება.",
    "surprises.preview.action": "სიურპრიზის წინასწარი ნახვა",
    "surprises.preview.note": "შენი არჩეული მომენტი, თემა და დეტალები ერთ წინასწარ ხედვაში. პირადი ბმული ჯერ არ იქმნება.",
    "surprises.demo.label": "ინტერაქტიული სიურპრიზის დემო · სანიმუშო შიგთავსი",
    "surprises.demo.aria": "სიურპრიზის თემები",
    "surprises.demo.description": "გახსენი, დაათვალიერე და სცადე ინტერაქციები. ფოტოები და ისტორიები ნიმუშებია; პასუხები და ცვლილებები არ ინახება.",
  },
};
for (const language of languages) Object.assign(captions[language], productCopy[language]);
