export const guestCanvasCopy = {
  en: {
    "guestCards.canvas.recommended": "Recommended",
    "guestCards.canvas.wording": "Card text",
    "guestCards.canvas.animations": "Animations",
    "guestCards.canvas.close": "Close animation choices",
    "guestCards.canvas.animationHint": "Choose how your invitation arrives. Try it as a guest whenever you like.",
    "guestCards.canvas.fineTune": "Fine-tune the celebration",
    "guestCards.canvas.tryAnimation": "Try this animation",
    "guestCards.canvas.tap": "Tap any text to edit",
    "guestCards.canvas.emptyText": "Add text",
    "guestCards.canvas.remove": "Remove {section}",
    "guestCards.canvas.addSection": "Add section",
    "guestCards.canvas.add": "Add",
    "guestCards.canvas.addNamed": "Add {section}",
    "guestCards.canvas.addHint": "Build your invitation right here. Choose a section, then edit it on the card.",
    "guestCards.canvas.added": "Added",
    "guestCards.canvas.section.details": "Recommended: help guests know when to arrive and where to go",
    "guestCards.canvas.section.plan": "Times and moments from your day",
    "guestCards.canvas.section.rsvp": "Recommended: collect guests’ first and last names and attendance",
    "guestCards.canvas.section.gallery": "Your favorite photos",
    "guestCards.canvas.section.notes": "A personal message with each reply",
    "guestCards.canvas.replySettings": "Reply settings",
    "guestCards.canvas.replyHint": "We recommend keeping this section to collect guests’ first and last names and attendance. Preview the invitation to try a reply.",
    "guestCards.canvas.guestName": "Your guest’s full name",
    "guestCards.canvas.addPhotos": "Add photos",
    "guestCards.canvas.sampleHint": "These are sample photos. Add your own photos here to replace them.",
    "guestCards.canvas.galleryEmpty": "Make this space yours. Add photos for your guests to enjoy.",
    "guestCards.canvas.editPlan": "Edit plan",
    "guestCards.canvas.done": "Done",
    "guestCards.canvas.saved": "Changes save on this device",
    "guestCards.canvas.preview": "Preview invitation",
    "guestCards.canvas.edit": "Back to editing",
  },
  ka: {
    "guestCards.canvas.recommended": "რეკომენდებულია",
    "guestCards.canvas.wording": "ბარათის ტექსტი",
    "guestCards.canvas.animations": "ანიმაციები",
    "guestCards.canvas.close": "ანიმაციების დახურვა",
    "guestCards.canvas.animationHint": "აირჩიე, როგორ გამოჩნდება მოსაწვევი. ნებისმიერ დროს ნახე ის სტუმრის თვალით.",
    "guestCards.canvas.fineTune": "ეფექტის დეტალები",
    "guestCards.canvas.tryAnimation": "ანიმაციის ნახვა",
    "guestCards.canvas.tap": "ტექსტის შესაცვლელად შეეხე მას",
    "guestCards.canvas.emptyText": "ტექსტის დამატება",
    "guestCards.canvas.remove": "წაშალე: {section}",
    "guestCards.canvas.addSection": "სექციის დამატება",
    "guestCards.canvas.add": "დამატება",
    "guestCards.canvas.addNamed": "დაამატე: {section}",
    "guestCards.canvas.addHint": "ააწყე მოსაწვევი აქვე. აირჩიე სექცია და შეცვალე ის პირდაპირ ბარათზე.",
    "guestCards.canvas.added": "დამატებულია",
    "guestCards.canvas.section.details": "ურჩიე სტუმრებს, როდის და სად მოვიდნენ",
    "guestCards.canvas.section.plan": "შენი დღის დროები და მომენტები",
    "guestCards.canvas.section.rsvp": "სასურველია სტუმრების სახელების, გვარებისა და დასწრების შეგროვება",
    "guestCards.canvas.section.gallery": "შენი საყვარელი ფოტოები",
    "guestCards.canvas.section.notes": "პირადი შეტყობინება თითოეულ პასუხთან",
    "guestCards.canvas.replySettings": "პასუხის პარამეტრები",
    "guestCards.canvas.replyHint": "გირჩევთ დატოვოთ ეს სექცია სტუმრების სახელების, გვარებისა და დასწრების შესაგროვებლად. პასუხის გამოსაცდელად ნახეთ მოსაწვევი.",
    "guestCards.canvas.guestName": "სტუმრის სახელი და გვარი",
    "guestCards.canvas.addPhotos": "ფოტოების დამატება",
    "guestCards.canvas.sampleHint": "ეს ნიმუშის ფოტოებია. ჩაანაცვლე ისინი შენი ფოტოებით აქვე.",
    "guestCards.canvas.galleryEmpty": "გააფორმე ეს სივრცე შენი ფოტოებით სტუმრებისთვის.",
    "guestCards.canvas.editPlan": "გეგმის შეცვლა",
    "guestCards.canvas.done": "მზადაა",
    "guestCards.canvas.saved": "ცვლილებები ამ მოწყობილობაზე ინახება",
    "guestCards.canvas.preview": "მოსაწვევის ნახვა",
    "guestCards.canvas.edit": "რედაქტირებაზე დაბრუნება",
  },
};
