import { guestCanvasCopy } from "./guestCanvasCopy.js";
import { invitationEditorCopy } from "./invitationEditorCopy.js";

export const guestCardCopy = {
  en: {
    ...invitationEditorCopy.en,
    ...guestCanvasCopy.en,
    "guestCards.preview": "Guest preview", "guestCards.back": "Back to design",
    "guestCards.desktop": "Desktop", "guestCards.mobile": "Mobile", "guestCards.device": "Preview size",
    "guestCards.gallery": "Photo gallery", "guestCards.motion": "Motion", "guestCards.options": "Options",
    "guestCards.format": "Main card format", "guestCards.square": "Square", "guestCards.portrait": "Portrait",
    "guestCards.motionStyle": "Animation style", "guestCards.motion.none": "Still",
    "guestCards.motion.gentle": "Gentle reveal", "guestCards.motion.float": "Floating ornaments", "guestCards.motion.sparkle": "Soft sparkle",
    "guestCards.motion.elegant": "Elegant reveal",
    "guestCards.entrance.portraitEnvelope": "Full-card envelope", "guestCards.entrance.envelope": "Envelope", "guestCards.entrance.doorsBrown": "Brown doors", "guestCards.entrance.doors": "Decorative doors", "guestCards.entrance.immediate": "Show immediately",
    "guestCards.doors.open": "Open invitation", "guestCards.doors.view": "View invitation", "guestCards.doors.opening": "Opening your invitation…",
    "guestCards.opening.title": "Opening animation", "guestCards.opening.none": "No opening effect", "guestCards.opening.confetti": "Confetti", "guestCards.opening.hearts": "Floating hearts", "guestCards.opening.sparkles": "Sparkles", "guestCards.opening.petals": "Falling petals",
    "guestCards.opening.density": "Amount", "guestCards.opening.subtle": "A little", "guestCards.opening.celebration": "A celebration",
    "guestCards.opening.duration": "Duration", "guestCards.opening.seconds": "{count} seconds", "guestCards.opening.colors": "Colors",
    "guestCards.opening.palette.theme": "Match the invitation", "guestCards.opening.palette.gold": "Warm gold", "guestCards.opening.palette.pastel": "Soft pastels", "guestCards.opening.replay": "Replay opening animation",
    "guestCards.envelope.entrance": "Invitation entrance", "guestCards.envelope.enabled": "Open from an envelope", "guestCards.envelope.direct": "Show the card immediately",
    "guestCards.envelope.forYou": "An invitation for you", "guestCards.envelope.open": "Open invitation", "guestCards.envelope.opened": "Invitation opened",
    "guestCards.opening.streamers": "Confetti & ribbon streamers",
    "guestCards.opening.speed": "Speed", "guestCards.opening.speed.dreamy": "Very slow", "guestCards.opening.speed.slow": "Slow", "guestCards.opening.speed.lively": "Lively",
    "guestCards.text.edit": "Edit invitation text", "guestCards.text.close": "Close text editor", "guestCards.text.hint": "Change the wording while keeping this design. Short lines fit the original layout best.",
    "guestCards.text.tapLabel": "Edit {label}", "guestCards.text.inlineTitle": "Edit card text", "guestCards.text.inlineSave": "Save changes", "guestCards.text.cancel": "Cancel",
    "guestCards.text.wording": "Other card wording", "guestCards.text.save": "Save invitation text", "guestCards.text.reset": "Restore sample text", "guestCards.text.variableHint": "Keep {token} to insert the current value.",
    "guestCards.text.title": "Invitation title", "guestCards.text.name": "Name", "guestCards.text.posterName": "Name", "guestCards.text.namePossessive": "Name wording",
    "guestCards.text.headline": "Main heading", "guestCards.text.heading": "Heading", "guestCards.text.opening": "Opening line", "guestCards.text.line": "Personal message",
    "guestCards.text.date": "Date", "guestCards.text.time": "Time", "guestCards.text.location": "Location", "guestCards.text.mark": "Initials or symbol", "guestCards.text.age": "Age", "guestCards.text.posterAge": "Age",
    "guestCards.text.posterOccasion": "Occasion", "guestCards.text.details": "Event details", "guestCards.text.ageLine": "Age line", "guestCards.text.ageWord": "Age wording",
    "guestCards.text.occasion": "Occasion heading", "guestCards.text.occasionSecond": "Second heading line", "guestCards.text.closing": "Closing line", "guestCards.text.menu": "Menu line",
    "guestCards.text.dressCode": "Dress code label", "guestCards.text.timeLabel": "Time label", "guestCards.text.locationLabel": "Location label", "guestCards.text.caption": "Caption", "guestCards.text.note": "Card note",
    "guestCards.text.step1": "Schedule wording 1", "guestCards.text.step2": "Schedule wording 2", "guestCards.text.step3": "Schedule wording 3", "guestCards.text.step4": "Schedule wording 4",
    "guestCards.companionsAllowed": "Additional guests allowed", "guestCards.noCompanions": "Just the invited guest",
    "guestCards.upTo": "Up to {count}", "guestCards.demo": "Interactive preview · replies stay on this device",
    "guestCards.invitation": "Invitation", "guestCards.details": "Details", "guestCards.rsvp": "RSVP", "guestCards.photos": "Photos",
    "guestCards.when": "When", "guestCards.where": "Where", "guestCards.map": "View map",
    "guestCards.plan.title": "Plan of the day", "guestCards.plan.hint": "Add the times and activities your guests should see. The card appears when you save a plan.",
    "guestCards.plan.moment": "Moment {count}", "guestCards.plan.time": "Time", "guestCards.plan.activity": "Activity",
    "guestCards.plan.details": "Details (optional)", "guestCards.plan.add": "+ Add a moment", "guestCards.plan.save": "Save plan",
    "guestCards.plan.clear": "Remove plan", "guestCards.plan.remove": "Remove moment {count}",
    "guestCards.plan.moveUp": "Move moment {count} up", "guestCards.plan.moveDown": "Move moment {count} down",
    "guestCards.plan.error": "Enter a time and an activity, or remove this moment.",
    "guestCards.plan.saved": "Saved. Your guests can now see the plan.", "guestCards.plan.hidden": "No plan saved. The card is hidden.",
    "guestCards.notes.title": "Guest notes", "guestCards.notes.allow": "Let guests leave a note", "guestCards.notes.choose": "Choose a prompt",
    "guestCards.notes.question": "Your question (optional)", "guestCards.notes.hint": "Your prompt appears in the separate Guest notes section. Leave the custom question blank to use the suggested wish prompt.",
    "guestCards.notes.preset.wish": "A wish for the hosts", "guestCards.notes.preset.memory": "A favorite memory", "guestCards.notes.preset.advice": "A little advice", "guestCards.notes.preset.custom": "Write your own question",
    "guestCards.notes.prompt.wish": "Leave us a wish", "guestCards.notes.prompt.memory": "Share a favorite memory", "guestCards.notes.prompt.advice": "Any advice for our next chapter?",
    "guestCards.notes.help.wish": "A few kind words or a wish for the day.", "guestCards.notes.help.memory": "A moment together that still makes you smile.",
    "guestCards.notes.help.advice": "Something you’d love us to remember.", "guestCards.notes.help.custom": "Write a personal message for the hosts. Up to 500 characters.", "guestCards.notes.optional": "optional",
    "guestCards.rsvp.title": "Save your seat", "guestCards.rsvp.question": "Will you be joining us?",
    "guestCards.fullName": "Full name", "guestCards.nameError": "Enter your full name to send your reply.",
    "guestCards.going": "Going", "guestCards.declined": "Can’t make it", "guestCards.comingWith": "Coming with you",
    "guestCards.fewer": "One fewer companion", "guestCards.more": "One more companion", "guestCards.companionCount": "Number of companions",
    "guestCards.seat": "1 seat in total", "guestCards.seats": "{count} seats in total",
    "guestCards.confirm": "Confirm reply", "guestCards.confirmed": "You’re on the list!", "guestCards.declineConfirmed": "Thank you for letting us know.",
    "guestCards.confirmedAlone": "We’ve saved your seat.", "guestCards.confirmedTogether": "You + {count} · {seats} seats saved.",
    "guestCards.edit": "Edit reply", "guestCards.savedLocally": "Preview reply saved on this device.",
    "guestCards.gallery.title": "A few favorite moments", "guestCards.gallery.sample": "Sample gallery",
    "guestCards.addPhotos": "Choose your photos", "guestCards.photoHint": "Up to 12 photos · JPG, PNG, WebP, GIF or AVIF · 8 MB each. Previewed on this device.",
    "guestCards.photoError": "Choose supported photos under 8 MB each. The gallery holds up to 12 photos.",
    "guestCards.photoUnreadable": "This photo couldn’t be opened. Please choose another.",
    "guestCards.resetPhotos": "Use sample photos", "guestCards.removePhoto": "Remove {name}",
    "guestCards.openPhoto": "Open photo: {name}", "guestCards.closePhoto": "Close photo", "guestCards.previousPhoto": "Previous photo", "guestCards.nextPhoto": "Next photo",
    "guestCards.photoNumber": "Photo {number}", "guestCards.photoPosition": "Photo {current} of {count}", "guestCards.made": "Made with 11:11",
    "guestCards.suite.title": "What your guests will see", "guestCards.suite.description": "Your invitation, the details, their reply — all in the same style. Add photos or a little motion if you like.",
    "guestCards.suite.action": "Preview guest cards",
    "guestCards.photos.birthday.0": "Make a wish", "guestCards.photos.birthday.1": "Our favorite people", "guestCards.photos.birthday.2": "A table full of joy",
    "guestCards.photos.wedding.0": "The little details", "guestCards.photos.wedding.1": "Better together", "guestCards.photos.wedding.2": "Our celebration",
    "guestCards.photos.bridal.0": "Good company", "guestCards.photos.bridal.1": "Girls forever", "guestCards.photos.bridal.2": "Sweet celebrations",
    "guestCards.photos.family.0": "Little beginnings", "guestCards.photos.family.1": "Together with love", "guestCards.photos.family.2": "A beautiful day",
  },
  ka: {
    ...invitationEditorCopy.ka,
    ...guestCanvasCopy.ka,
    "guestCards.preview": "სტუმრის ხედი", "guestCards.back": "დიზაინზე დაბრუნება",
    "guestCards.desktop": "კომპიუტერი", "guestCards.mobile": "მობილური", "guestCards.device": "ხედის ზომა",
    "guestCards.gallery": "ფოტოგალერეა", "guestCards.motion": "ანიმაცია", "guestCards.options": "პარამეტრები",
    "guestCards.format": "მთავარი ბარათის ფორმატი", "guestCards.square": "კვადრატი", "guestCards.portrait": "ვერტიკალური",
    "guestCards.motionStyle": "ანიმაციის სტილი", "guestCards.motion.none": "უძრავი",
    "guestCards.motion.gentle": "ნაზი გამოჩენა", "guestCards.motion.float": "მოძრავი ორნამენტები", "guestCards.motion.sparkle": "მსუბუქი ციმციმი",
    "guestCards.motion.elegant": "ელეგანტური გამოჩენა",
    "guestCards.entrance.portraitEnvelope": "სრული ბარათის კონვერტი", "guestCards.entrance.envelope": "კონვერტი", "guestCards.entrance.doorsBrown": "ყავისფერი კარები", "guestCards.entrance.doors": "დეკორატიული კარები", "guestCards.entrance.immediate": "პირდაპირ ჩვენება",
    "guestCards.doors.open": "მოსაწვევის გახსნა", "guestCards.doors.view": "მოსაწვევის ნახვა", "guestCards.doors.opening": "შენი მოსაწვევი იხსნება…",
    "guestCards.opening.title": "გახსნის ანიმაცია", "guestCards.opening.none": "გახსნის ეფექტის გარეშე", "guestCards.opening.confetti": "კონფეტი", "guestCards.opening.hearts": "გულები", "guestCards.opening.sparkles": "ციმციმი", "guestCards.opening.petals": "ჩამოცვენილი ფურცლები",
    "guestCards.opening.density": "რაოდენობა", "guestCards.opening.subtle": "მსუბუქი", "guestCards.opening.celebration": "საზეიმო",
    "guestCards.opening.duration": "ხანგრძლივობა", "guestCards.opening.seconds": "{count} წამი", "guestCards.opening.colors": "ფერები",
    "guestCards.opening.palette.theme": "მოსაწვევის ფერები", "guestCards.opening.palette.gold": "თბილი ოქროსფერი", "guestCards.opening.palette.pastel": "ნაზი პასტელი", "guestCards.opening.replay": "გახსნის ანიმაციის გამეორება",
    "guestCards.envelope.entrance": "მოსაწვევის გამოჩენა", "guestCards.envelope.enabled": "კონვერტიდან გახსნა", "guestCards.envelope.direct": "ბარათის პირდაპირ ჩვენება",
    "guestCards.envelope.forYou": "მოსაწვევი შენთვის", "guestCards.envelope.open": "მოსაწვევის გახსნა", "guestCards.envelope.opened": "მოსაწვევი გაიხსნა",
    "guestCards.opening.streamers": "კონფეტი და ლენტები",
    "guestCards.opening.speed": "სიჩქარე", "guestCards.opening.speed.dreamy": "ძალიან ნელი", "guestCards.opening.speed.slow": "ნელი", "guestCards.opening.speed.lively": "სწრაფი",
    "guestCards.text.edit": "მოსაწვევის ტექსტის შეცვლა", "guestCards.text.close": "ტექსტის რედაქტორის დახურვა", "guestCards.text.hint": "შეცვალე ტექსტი ამ დიზაინის შენარჩუნებით. მოკლე სტრიქონები ბარათში უკეთ ეტევა.",
    "guestCards.text.tapLabel": "შეცვალე: {label}", "guestCards.text.inlineTitle": "ბარათის ტექსტის შეცვლა", "guestCards.text.inlineSave": "ცვლილებების შენახვა", "guestCards.text.cancel": "გაუქმება",
    "guestCards.text.wording": "ბარათის სხვა ტექსტები", "guestCards.text.save": "მოსაწვევის ტექსტის შენახვა", "guestCards.text.reset": "ნიმუშის ტექსტის აღდგენა", "guestCards.text.variableHint": "შეინარჩუნე {token}, რომ მიმდინარე მნიშვნელობა გამოჩნდეს.",
    "guestCards.text.title": "მოსაწვევის სათაური", "guestCards.text.name": "სახელი", "guestCards.text.posterName": "სახელი", "guestCards.text.namePossessive": "სახელის ფორმა",
    "guestCards.text.headline": "მთავარი სათაური", "guestCards.text.heading": "სათაური", "guestCards.text.opening": "შესავალი", "guestCards.text.line": "პირადი ტექსტი",
    "guestCards.text.date": "თარიღი", "guestCards.text.time": "დრო", "guestCards.text.location": "ადგილი", "guestCards.text.mark": "ინიციალები ან სიმბოლო", "guestCards.text.age": "ასაკი", "guestCards.text.posterAge": "ასაკი",
    "guestCards.text.posterOccasion": "ღონისძიება", "guestCards.text.details": "ღონისძიების დეტალები", "guestCards.text.ageLine": "ასაკის ტექსტი", "guestCards.text.ageWord": "ასაკის ფორმულირება",
    "guestCards.text.occasion": "ღონისძიების სათაური", "guestCards.text.occasionSecond": "სათაურის მეორე ხაზი", "guestCards.text.closing": "დასასრული", "guestCards.text.menu": "მენიუს ხაზი",
    "guestCards.text.dressCode": "ჩაცმულობის წარწერა", "guestCards.text.timeLabel": "დროის წარწერა", "guestCards.text.locationLabel": "ადგილის წარწერა", "guestCards.text.caption": "წარწერა", "guestCards.text.note": "ბარათის ჩანაწერი",
    "guestCards.text.step1": "გეგმის ტექსტი 1", "guestCards.text.step2": "გეგმის ტექსტი 2", "guestCards.text.step3": "გეგმის ტექსტი 3", "guestCards.text.step4": "გეგმის ტექსტი 4",
    "guestCards.companionsAllowed": "თანმხლები სტუმრების რაოდენობა", "guestCards.noCompanions": "მხოლოდ მოწვეული სტუმარი",
    "guestCards.upTo": "მაქსიმუმ {count}", "guestCards.demo": "ინტერაქტიული ნიმუში · პასუხები ამ მოწყობილობაზე რჩება",
    "guestCards.invitation": "მოსაწვევი", "guestCards.details": "დეტალები", "guestCards.rsvp": "პასუხი", "guestCards.photos": "ფოტოები",
    "guestCards.when": "როდის", "guestCards.where": "სად", "guestCards.map": "რუკის ნახვა",
    "guestCards.plan.title": "დღის გეგმა", "guestCards.plan.hint": "დაამატე დრო და აქტივობები, რომლებსაც სტუმრები ნახავენ. ბარათი გეგმის შენახვის შემდეგ გამოჩნდება.",
    "guestCards.plan.moment": "ეტაპი {count}", "guestCards.plan.time": "დრო", "guestCards.plan.activity": "აქტივობა",
    "guestCards.plan.details": "დეტალები (არასავალდებულო)", "guestCards.plan.add": "+ ეტაპის დამატება", "guestCards.plan.save": "გეგმის შენახვა",
    "guestCards.plan.clear": "გეგმის წაშლა", "guestCards.plan.remove": "წაშალე ეტაპი {count}",
    "guestCards.plan.moveUp": "აწიე ეტაპი {count}", "guestCards.plan.moveDown": "ჩამოწიე ეტაპი {count}",
    "guestCards.plan.error": "შეიყვანე დრო და აქტივობა, ან წაშალე ეს ეტაპი.",
    "guestCards.plan.saved": "შენახულია. სტუმრები დღის გეგმას ნახავენ.", "guestCards.plan.hidden": "გეგმა არ არის შენახული. ბარათი დამალულია.",
    "guestCards.notes.title": "სტუმრების ჩანაწერები", "guestCards.notes.allow": "სტუმრებს ჩანაწერის დატოვება შეეძლოთ", "guestCards.notes.choose": "აირჩიე შეკითხვა",
    "guestCards.notes.question": "შენი შეკითხვა (არასავალდებულო)", "guestCards.notes.hint": "შეკითხვა სტუმრების ჩანაწერების ცალკე სექციაში გამოჩნდება. თუ შენს შეკითხვას არ შეიყვან, სურვილის დატოვების შეთავაზება გამოჩნდება.",
    "guestCards.notes.preset.wish": "სურვილი მასპინძლებს", "guestCards.notes.preset.memory": "საყვარელი მოგონება", "guestCards.notes.preset.advice": "პატარა რჩევა", "guestCards.notes.preset.custom": "დაწერე შენი შეკითხვა",
    "guestCards.notes.prompt.wish": "დაგვიტოვე სურვილი", "guestCards.notes.prompt.memory": "გაგვიზიარე საყვარელი მოგონება", "guestCards.notes.prompt.advice": "რას გვირჩევ ჩვენი ახალი ეტაპისთვის?",
    "guestCards.notes.help.wish": "რამდენიმე თბილი სიტყვა ან სურვილი ამ დღისთვის.", "guestCards.notes.help.memory": "ერთად გატარებული მომენტი, რომელიც დღესაც გაღიმებს.",
    "guestCards.notes.help.advice": "რამე, რაც გინდა, რომ გვახსოვდეს.", "guestCards.notes.help.custom": "დაწერე პირადი შეტყობინება მასპინძლებს. მაქსიმუმ 500 სიმბოლო.", "guestCards.notes.optional": "არასავალდებულო",
    "guestCards.rsvp.title": "შეინახე შენი ადგილი", "guestCards.rsvp.question": "შემოგვიერთდები?",
    "guestCards.fullName": "სახელი და გვარი", "guestCards.nameError": "პასუხის გასაგზავნად შეიყვანე შენი სახელი და გვარი.",
    "guestCards.going": "მოვდივარ", "guestCards.declined": "ვერ მოვდივარ", "guestCards.comingWith": "ვინ მოდის შენთან ერთად",
    "guestCards.fewer": "ერთით ნაკლები თანმხლები", "guestCards.more": "ერთით მეტი თანმხლები", "guestCards.companionCount": "თანმხლებთა რაოდენობა",
    "guestCards.seat": "სულ 1 ადგილი", "guestCards.seats": "სულ {count} ადგილი",
    "guestCards.confirm": "პასუხის დადასტურება", "guestCards.confirmed": "შენ სიაში ხარ!", "guestCards.declineConfirmed": "მადლობა, რომ შეგვატყობინე.",
    "guestCards.confirmedAlone": "შენი ადგილი შენახულია.", "guestCards.confirmedTogether": "შენ და {count} თანმხლები · შენახულია {seats} ადგილი.",
    "guestCards.edit": "პასუხის შეცვლა", "guestCards.savedLocally": "ნიმუშის პასუხი ამ მოწყობილობაზე შეინახა.",
    "guestCards.gallery.title": "რამდენიმე საყვარელი მომენტი", "guestCards.gallery.sample": "გალერეის ნიმუში",
    "guestCards.addPhotos": "აირჩიე შენი ფოტოები", "guestCards.photoHint": "მაქსიმუმ 12 ფოტო · თითოეული 8 მბ-მდე. ფოტოები მხოლოდ ამ მოწყობილობაზე ჩანს.",
    "guestCards.photoError": "აირჩიე მხარდაჭერილი ფოტოები, თითოეული 8 მბ-მდე. გალერეაში მაქსიმუმ 12 ფოტო ეტევა.",
    "guestCards.photoUnreadable": "ფოტო ვერ გაიხსნა. გთხოვ, აირჩიე სხვა.",
    "guestCards.resetPhotos": "ნიმუშის ფოტოების გამოყენება", "guestCards.removePhoto": "წაშალე {name}",
    "guestCards.openPhoto": "ფოტოს გახსნა: {name}", "guestCards.closePhoto": "ფოტოს დახურვა", "guestCards.previousPhoto": "წინა ფოტო", "guestCards.nextPhoto": "შემდეგი ფოტო",
    "guestCards.photoNumber": "ფოტო {number}", "guestCards.photoPosition": "ფოტო {current} / {count}", "guestCards.made": "შექმნილია 11:11-ით",
    "guestCards.suite.title": "რას ნახავენ შენი სტუმრები", "guestCards.suite.description": "მოსაწვევი, დეტალები და სტუმრის პასუხი — ერთ სტილში. სურვილისამებრ დაამატე ფოტოები და მსუბუქი ანიმაცია.",
    "guestCards.suite.action": "სტუმრის ბარათების ნახვა",
    "guestCards.photos.birthday.0": "ჩაიფიქრე სურვილი", "guestCards.photos.birthday.1": "საყვარელი ადამიანები", "guestCards.photos.birthday.2": "სიხარულით სავსე სუფრა",
    "guestCards.photos.wedding.0": "პატარა დეტალები", "guestCards.photos.wedding.1": "ერთად უკეთესია", "guestCards.photos.wedding.2": "ჩვენი ზეიმი",
    "guestCards.photos.bridal.0": "კარგი მეგობრები", "guestCards.photos.bridal.1": "მეგობრები მუდამ", "guestCards.photos.bridal.2": "ტკბილი დღესასწაული",
    "guestCards.photos.family.0": "პატარა დასაწყისი", "guestCards.photos.family.1": "ერთად, სიყვარულით", "guestCards.photos.family.2": "ლამაზი დღე",
  },
};
