export const invitationEditorCopy = {
  en: {
    'customCollection.eyebrow': 'A blank canvas for your celebration',
    'customCollection.heading': 'Create your own design',
    'customCollection.intro': 'Start from your own idea in any collection. Add your words, cover photo, colors and opening animation.',
    'customCollection.card': 'Your custom invitation',
    'customCollection.start': 'Start creating',
    'customCollection.yourStory': 'Your story, your style',
    'customCollection.oneOfOne': 'Made by you',
    'editor.title': 'Make it yours',
    'editor.intro': 'Answer a few questions and watch your invitation take shape.',
    'editor.guide': 'Guided setup',
    'guide.progress': 'Invitation setup progress',
    'guide.count': 'Step {current} of {total}',
    'guide.step.people': 'The people', 'guide.step.event': 'The day', 'guide.step.story': 'Your words', 'guide.step.design': 'Design', 'guide.step.guests': 'Guests', 'guide.step.opening': 'The opening',
    'guide.title.people': 'Who are we celebrating?', 'guide.title.event': 'When and where is the celebration?', 'guide.title.story': 'What would you like to say?', 'guide.title.design': 'Make the design yours', 'guide.title.guests': 'What should guests be able to do?', 'guide.title.opening': 'How should your invitation open?',
    'guide.intro.people': 'Start with the names. They will appear throughout your invitation.',
    'guide.intro.event': 'Add the date, time and place. You can include a full schedule too.',
    'guide.intro.story': 'Make the message personal.',
    'guide.intro.design': 'Start with your chosen design, then add a photo cover and a frame if you like.',
    'guide.intro.guests': 'Choose the sections guests will see and how RSVP works.',
    'guide.intro.opening': 'Keep your envelope, open the decorative doors or start immediately. Add a celebration effect, then preview it as a guest.',
    'guide.firstName': 'First partner’s name', 'guide.secondName': 'Second partner’s name',
    'guide.namesHint': 'The names on the card and its initials update together.',
    'guide.schedule': 'Add a schedule (optional)', 'guide.photos': 'Add your photos',
    'guide.photosHint': 'Photos appear in the gallery in this preview.', 'guide.photoCount': '{count} of {max} photos added',
    'guide.advancedAnimation': 'Fine tune animation', 'guide.readyTitle': 'See the guest experience',
    'guide.readyHint': 'Play the opening and celebration. This visual draft is saved on this device.',
    'guide.previewGuest': 'Preview as a guest', 'guide.replay': 'Replay opening', 'guide.back': 'Back', 'guide.continue': 'Continue',
    'editor.card': 'Edit on card', 'editor.form': 'Fill out form', 'editor.animations': 'Animations', 'editor.sections': 'Guest sections',
    'editor.cardHint': 'Tap any wording on the invitation to change it. Use the form if you prefer labels and examples.',
    'editor.detailsTitle': 'Invitation details', 'editor.detailsHint': 'Replace the sample details with your own. Your card updates as you type.',
    'editor.who': 'Who & what', 'editor.when': 'When & where', 'editor.words': 'Card wording', 'editor.moreWords': 'Section wording & extra text',
    'editor.live': 'Changes appear on your card as you type.', 'editor.viewCard': 'View my card',
    'editor.optional': 'Optional', 'editor.example': 'Example: {value}', 'editor.datePicker': 'Choose a date',
    'editor.help.name': 'The name of the person or people you are celebrating.',
    'editor.help.age': 'The age they are turning. Enter a number, such as 7 or 30.',
    'editor.help.title': 'The event name. Some designs use this as the invitation title; others use it in the guest preview.',
    'editor.help.headline': 'The main words on the card. Keep them short; line breaks are welcome.',
    'editor.help.opening': 'A short introduction or occasion, such as Birthday edition or You’re invited.',
    'editor.help.date': 'The event date as you want guests to see it. You can type it or choose from the calendar.',
    'editor.help.time': 'When guests should arrive, for example 14:00 or 7 PM.',
    'editor.help.location': 'Add the venue name or full address so guests know where to go.',
    'editor.help.line': 'A short personal message, such as Join us for cake and good company.',
    'editor.help.details': 'Any extra details guests should know, such as the address or dress code.',
    'editor.help.namePossessive': 'How the name appears before the occasion, for example Mia’s. Usually this follows the name automatically.',
    'editor.help.mark': 'A small number, symbol, or short accent on the card.',
    'editor.help.posterOccasion': 'The occasion beside the name, for example Birthday Party.',
    'editor.help.wording': 'Change this phrase on the invitation. Short wording fits the design best.',
    'editor.help.section': 'This wording appears in the guest section, rather than on the main invitation.',
    'editor.help.notePrompt': 'The question guests can answer when they send their reply.',
    'editor.help.planTitle': 'The name of this part of the day, such as Dinner or First dance.',
    'editor.chars': '{count} / {max} characters',
    'editor.animationTitle': 'Bring your invitation to life',
    'editor.animationHint': 'Choose how it opens, add a celebration, then decide how the page moves. Each part is optional.',
    'editor.opening': 'Opening', 'editor.celebration': 'Celebration', 'editor.motion': 'Page motion',
    'editor.openingHint': 'What guests see before they read the invitation.',
    'editor.celebrationHint': 'A brief effect when the invitation opens.',
    'editor.motionHint': 'How the invitation’s sections and decorations move as guests browse.',
    'editor.entrance.portraitEnvelope': 'Paper folds open across the whole invitation card.',
    'editor.entrance.envelope': 'Guests tap an envelope to reveal your card.',
    'editor.entrance.doors': 'Classical white doors open to reveal the invitation.',
    'editor.entrance.doorsBrown': 'Classical walnut doors open to reveal the invitation.',
    'editor.entrance.immediate': 'Show the card right away, with no opening step.',
    'editor.effect.none': 'Keep the opening simple, with no extra effect.',
    'editor.effect.confetti': 'Colorful pieces fall as the invitation opens.',
    'editor.effect.streamers': 'Confetti and ribbons for a lively celebration.',
    'editor.effect.hearts': 'Hearts drift gently across the screen.',
    'editor.effect.sparkles': 'Small points of light for a subtle shimmer.',
    'editor.effect.petals': 'Soft petals float across the invitation.',
    'editor.motion.none': 'Everything stays still. A calm, simple choice.',
    'editor.motion.gentle': 'Sections appear softly as guests scroll.',
    'editor.motion.float': 'Decorative details move gently.',
    'editor.motion.sparkle': 'A light sparkle around the decorations.',
    'editor.motion.elegant': 'A coordinated reveal with slow, subtle movement.',
    'editor.previewAnimation': 'Preview animation', 'editor.previewHelp': 'See the actual guest experience. Use Back to editing to return to these choices.',
    'editor.backEditing': 'Back to editing', 'editor.fineTune': 'Adjust speed, amount & colors',
    'editor.sectionsTitle': 'What should guests see?', 'editor.sectionsHint': 'Add the sections you need. You can change or remove them on the page.',
    'editor.replySettingsHint': 'Choose how many extra people each invited guest can bring. Guests will see a simple attendance form.',
    'editor.extraGuests': 'Extra guests per reply', 'editor.justGuest': 'Just the invited guest', 'editor.oneExtraGuest': '+1 extra guest', 'editor.extraGuestCount': '+{count} extra guests',
    'editor.replySingleSummary': 'Each reply reserves one seat. Guests won’t be asked about companions.', 'editor.replyGroupSummary': 'Each reply can reserve up to {count} seats, including the invited guest.', 'editor.settingsAutoSave': 'Changes save automatically and update the form below.',
    'editor.countdown': 'Counting down to the day', 'editor.days': 'Days', 'editor.hours': 'Hours', 'editor.minutes': 'Minutes', 'editor.seconds': 'Seconds',
    'editor.eventZone': 'Event time zone', 'editor.zoneHint': 'Choose where the event takes place. The countdown and calendar use this time zone.',
    'editor.eventStarted': 'The day is here!', 'editor.addCalendar': 'Add to calendar', 'editor.calendarFile': 'Apple / Outlook / other calendar (.ics)',
    'editor.calendarHint': 'Open the file in your calendar and confirm to add the event.', 'editor.dateNeeded': 'Enter a full date with a year and a time such as 14:00 to show the countdown and calendar.', 'editor.dateComing': 'Event date coming soon.',
    'editor.sendNote': 'Save my note', 'editor.noteSaved': 'Your note is saved. Thank you!',
    'editor.goSection': 'Go to section', 'editor.addSection': 'Add section',
    'editor.saved': 'Changes save on this device', 'editor.updated': 'Updated on your card',
    'editor.previewNotice': 'You’re viewing the invitation as a guest. Return to editing to make changes.',
    'editor.editThis': 'Edit this text',
  },
  ka: {
    'customCollection.eyebrow': 'სუფთა ფურცელი შენი დღესასწაულისთვის',
    'customCollection.heading': 'შექმენი საკუთარი დიზაინი',
    'customCollection.intro': 'დაიწყე საკუთარი იდეით ნებისმიერ კოლექციაში. დაამატე ტექსტი, ყდის ფოტო, ფერები და გახსნის ანიმაცია.',
    'customCollection.card': 'შენი პირადი მოსაწვევი',
    'customCollection.start': 'დაწყება',
    'customCollection.yourStory': 'შენი ისტორია, შენი სტილი',
    'customCollection.oneOfOne': 'შენ მიერ შექმნილი',
    'editor.title': 'მოარგე შენს დღეს',
    'editor.intro': 'უპასუხე რამდენიმე კითხვას და ნახე, როგორ იქმნება შენი მოსაწვევი.',
    'editor.guide': 'ნაბიჯ-ნაბიჯ შექმნა',
    'guide.progress': 'მოსაწვევის შექმნის ნაბიჯები',
    'guide.count': 'ნაბიჯი {current} / {total}',
    'guide.step.people': 'სახელები', 'guide.step.event': 'დღე', 'guide.step.story': 'ტექსტი', 'guide.step.design': 'დიზაინი', 'guide.step.guests': 'სტუმრები', 'guide.step.opening': 'გახსნა',
    'guide.title.people': 'ვის ვულოცავთ ამ დღეს?', 'guide.title.event': 'როდის და სად გაიმართება?', 'guide.title.story': 'რა გინდა უთხრა სტუმრებს?', 'guide.title.design': 'მოარგე დიზაინი შენს დღეს', 'guide.title.guests': 'რა შეძლონ სტუმრებმა?', 'guide.title.opening': 'როგორ გაიხსნას მოსაწვევი?',
    'guide.intro.people': 'დაიწყე სახელებით. ისინი მთელ მოსაწვევში გამოჩნდება.',
    'guide.intro.event': 'დაამატე თარიღი, დრო და ადგილი. სურვილის შემთხვევაში დღის განრიგიც შეავსე.',
    'guide.intro.story': 'მოარგე ტექსტი შენს ისტორიას.',
    'guide.intro.design': 'დაიწყე არჩეული დიზაინით და სურვილისამებრ დაამატე ფოტო და ჩარჩო.',
    'guide.intro.guests': 'აირჩიე სექციები, რომლებსაც სტუმრები ნახავენ, და დააყენე RSVP.',
    'guide.intro.opening': 'შეინარჩუნე კონვერტი, გახსენი დეკორატიული კარები ან პირდაპირ აჩვენე ბარათი. შემდეგ სტუმრის ხედით ნახე ეფექტი.',
    'guide.firstName': 'პირველი ადამიანის სახელი', 'guide.secondName': 'მეორე ადამიანის სახელი',
    'guide.namesHint': 'ბარათზე სახელები და ინიციალები ერთად განახლდება.',
    'guide.schedule': 'დღის განრიგის დამატება (არასავალდებულო)', 'guide.photos': 'ფოტოების დამატება',
    'guide.photosHint': 'ფოტოები ამ პრევიუს გალერეაში გამოჩნდება.', 'guide.photoCount': 'დამატებულია {count} / {max} ფოტო',
    'guide.advancedAnimation': 'ანიმაციის დეტალური მორგება', 'guide.readyTitle': 'ნახე სტუმრის გამოცდილება',
    'guide.readyHint': 'ნახე გახსნისა და სადღესასწაულო ეფექტი. ეს ვიზუალური მონახაზი ამ მოწყობილობაზე ინახება.',
    'guide.previewGuest': 'სტუმრის ხედით ნახვა', 'guide.replay': 'გახსნის გამეორება', 'guide.back': 'უკან', 'guide.continue': 'გაგრძელება',
    'editor.card': 'ბარათზე შეცვლა', 'editor.form': 'ფორმის შევსება', 'editor.animations': 'ანიმაციები', 'editor.sections': 'სტუმრის სექციები',
    'editor.cardHint': 'ტექსტის შესაცვლელად დააჭირე მას მოსაწვევზე. თუ გირჩევნია ახსნა და მაგალითები, გამოიყენე ფორმა.',
    'editor.detailsTitle': 'მოსაწვევის დეტალები', 'editor.detailsHint': 'შეცვალე მაგალითის მონაცემები შენით. ბარათი წერისას ახლდება.',
    'editor.who': 'ვინ და რა', 'editor.when': 'როდის და სად', 'editor.words': 'ბარათის ტექსტი', 'editor.moreWords': 'სექციებისა და დამატებითი ტექსტი',
    'editor.live': 'ცვლილებები წერისას აისახება ბარათზე.', 'editor.viewCard': 'ჩემი ბარათის ნახვა',
    'editor.optional': 'არასავალდებულო', 'editor.example': 'მაგალითი: {value}', 'editor.datePicker': 'თარიღის არჩევა',
    'editor.help.name': 'ვის აღნიშნავთ — ადამიანის ან წყვილის სახელი.',
    'editor.help.age': 'რამდენი წლის ხდება. ჩაწერე რიცხვი, მაგალითად 7 ან 30.',
    'editor.help.title': 'ღონისძიების სახელი. ზოგ დიზაინში ბარათზე ჩანს, ზოგში — სტუმრის ხედში.',
    'editor.help.headline': 'ბარათის მთავარი წარწერა. მოკლე ტექსტი უკეთ ეტევა; შეგიძლია ახალ ხაზზე გადასვლაც.',
    'editor.help.opening': 'მოკლე შესავალი ან მიზეზი, მაგალითად გეპატიჟებით ან დაბადების დღე.',
    'editor.help.date': 'თარიღი ისე, როგორც სტუმრებმა უნდა ნახონ. ჩაწერე ან აირჩიე კალენდარში.',
    'editor.help.time': 'როდის უნდა მოვიდნენ სტუმრები, მაგალითად 14:00 ან 19:00.',
    'editor.help.location': 'ჩაწერე ადგილის სახელი ან სრული მისამართი.',
    'editor.help.line': 'მოკლე პირადი ტექსტი, მაგალითად გელოდებით ტორტით და კარგი განწყობით.',
    'editor.help.details': 'დამატებითი ინფორმაცია სტუმრებისთვის, მაგალითად მისამართი ან ჩაცმულობა.',
    'editor.help.namePossessive': 'სახელი სათაურში, მაგალითად მიას. ჩვეულებრივ სახელს ავტომატურად მიჰყვება.',
    'editor.help.mark': 'მცირე რიცხვი, სიმბოლო ან მოკლე აქცენტი ბარათზე.',
    'editor.help.posterOccasion': 'ღონისძიების სახელი სახელთან ერთად, მაგალითად დაბადების დღე.',
    'editor.help.wording': 'შეცვალე ეს ფრაზა ბარათზე. მოკლე ტექსტი დიზაინს უკეთ ერგება.',
    'editor.help.section': 'ეს ტექსტი სტუმრის სექციაში გამოჩნდება და არა მთავარ ბარათზე.',
    'editor.help.notePrompt': 'კითხვა, რომელსაც სტუმრები პასუხის გაგზავნისას უპასუხებენ.',
    'editor.help.planTitle': 'დღის ამ ნაწილის სახელი, მაგალითად ვახშამი ან პირველი ცეკვა.',
    'editor.chars': '{count} / {max} სიმბოლო',
    'editor.animationTitle': 'გააცოცხლე მოსაწვევი',
    'editor.animationHint': 'აირჩიე გახსნა, სადღესასწაულო ეფექტი და გვერდის მოძრაობა. თითოეული არჩევითია.',
    'editor.opening': 'გახსნა', 'editor.celebration': 'ეფექტი', 'editor.motion': 'მოძრაობა',
    'editor.openingHint': 'რას ხედავენ სტუმრები მოსაწვევის წაკითხვამდე.',
    'editor.celebrationHint': 'მოკლე ეფექტი მოსაწვევის გახსნისას.',
    'editor.motionHint': 'როგორ მოძრაობს სექციები და დეკორაციები დათვალიერებისას.',
    'editor.entrance.portraitEnvelope': 'ქაღალდის კონვერტი მთელ მოსაწვევს ფარავს და შეხებით იხსნება.',
    'editor.entrance.envelope': 'სტუმარი კონვერტზე დაჭერით გახსნის ბარათს.',
    'editor.entrance.doors': 'კლასიკური თეთრი კარები იხსნება და მოსაწვევი ჩნდება.',
    'editor.entrance.doorsBrown': 'კლასიკური ყავისფერი კარები იხსნება და მოსაწვევი ჩნდება.',
    'editor.entrance.immediate': 'ბარათი მაშინვე ჩანს, გახსნის დამატებითი ნაბიჯის გარეშე.',
    'editor.effect.none': 'მარტივი გახსნა დამატებითი ეფექტის გარეშე.',
    'editor.effect.confetti': 'გახსნისას ფერადი კონფეტი ცვივა.',
    'editor.effect.streamers': 'კონფეტი და ლენტები მხიარული დღესასწაულისთვის.',
    'editor.effect.hearts': 'გულები ნელა მოძრაობს ეკრანზე.',
    'editor.effect.sparkles': 'მცირე ნათებები მსუბუქი ბზინვარებისთვის.',
    'editor.effect.petals': 'რბილი ფურცლები მოსაწვევის გარშემო.',
    'editor.motion.none': 'ყველაფერი უძრავია. მშვიდი და მარტივი არჩევანი.',
    'editor.motion.gentle': 'სექციები ნაზად ჩნდება ჩამოსქროლვისას.',
    'editor.motion.float': 'დეკორაციები მსუბუქად მოძრაობს.',
    'editor.motion.sparkle': 'მსუბუქი ბზინვარება დეკორაციების გარშემო.',
    'editor.motion.elegant': 'ნაზი გამოჩენა და ნელი, მსუბუქი მოძრაობა.',
    'editor.previewAnimation': 'ანიმაციის ნახვა', 'editor.previewHelp': 'ნახე სტუმრის რეალური გამოცდილება. არჩევანთან დასაბრუნებლად დააჭირე რედაქტირებაზე დაბრუნებას.',
    'editor.backEditing': 'რედაქტირებაზე დაბრუნება', 'editor.fineTune': 'სიჩქარე, რაოდენობა და ფერები',
    'editor.sectionsTitle': 'რას ნახავენ სტუმრები?', 'editor.sectionsHint': 'დაამატე საჭირო სექციები. გვერდზე შეგიძლია შეცვლა ან წაშლა.',
    'editor.replySettingsHint': 'აირჩიე, რამდენი დამატებითი ადამიანი შეუძლია თითოეულ მოწვეულ სტუმარს წამოიყვანოს. სტუმრები დასწრების მარტივ ფორმას შეავსებენ.',
    'editor.extraGuests': 'დამატებითი სტუმრები თითოეულ პასუხში', 'editor.justGuest': 'მხოლოდ მოწვეული სტუმარი', 'editor.oneExtraGuest': '+1 დამატებითი სტუმარი', 'editor.extraGuestCount': '+{count} დამატებითი სტუმარი',
    'editor.replySingleSummary': 'თითოეული პასუხი ერთ ადგილს ინახავს. თანმხლებებზე შეკითხვა არ გამოჩნდება.', 'editor.replyGroupSummary': 'თითოეულ პასუხში მაქსიმუმ {count} ადგილი შეინახება, მოწვეული სტუმრის ჩათვლით.', 'editor.settingsAutoSave': 'ცვლილება ავტომატურად ინახება და პასუხის ფორმაში აისახება.',
    'editor.countdown': 'დღემდე დარჩენილია', 'editor.days': 'დღე', 'editor.hours': 'საათი', 'editor.minutes': 'წუთი', 'editor.seconds': 'წამი',
    'editor.eventZone': 'ღონისძიების დროის სარტყელი', 'editor.zoneHint': 'აირჩიე ღონისძიების ადგილი. უკუთვლა და კალენდარი ამ დროის სარტყელს გამოიყენებს.',
    'editor.eventStarted': 'ეს დღე დადგა!', 'editor.addCalendar': 'კალენდარში დამატება', 'editor.calendarFile': 'Apple / Outlook / სხვა კალენდარი (.ics)',
    'editor.calendarHint': 'გახსენი ფაილი შენს კალენდარში და დაადასტურე დამატება.', 'editor.dateNeeded': 'შეიყვანე სრული თარიღი წლით და დრო, მაგალითად 14:00, უკუთვლისა და კალენდრისთვის.', 'editor.dateComing': 'ღონისძიების თარიღი მალე გამოჩნდება.',
    'editor.sendNote': 'ჩანაწერის შენახვა', 'editor.noteSaved': 'შენი ჩანაწერი შენახულია. მადლობა!',
    'editor.goSection': 'სექციაზე გადასვლა', 'editor.addSection': 'სექციის დამატება',
    'editor.saved': 'ცვლილებები ამ მოწყობილობაზე ინახება', 'editor.updated': 'ბარათზე განახლდა',
    'editor.previewNotice': 'ახლა მოსაწვევს სტუმრის ხედით ათვალიერებ. ცვლილებისთვის დაბრუნდი რედაქტირებაზე.',
    'editor.editThis': 'ამ ტექსტის შეცვლა',
  },
};
