import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { useLanguage } from '../../localization/LanguageContext.jsx';
import RibbonSketchToolbar from '../ribbon-sketch/RibbonSketchToolbar.jsx';
import InvitationArtwork from '../components/InvitationArtwork.jsx';
import { ribbonPhotos, ribbonPhotoCaptions } from '../ribbon-sketch/assets.js';
import '../ribbon-sketch/fonts.css';
import '../../styles/checkerboard-cheers.css';

const martini='/images/birthday/checkerboard-cheers/painted-olive-martini.webp';
const spritz='/images/components/separated/checkerboard-spritz.webp';
const drinks=[martini,spritz];
const citrusCoupe='/images/birthday/checkerboard-cheers/experience/orange-coupe.webp';
const pinkCitrus='/images/birthday/checkerboard-cheers/experience/grapefruit-highball.webp';
const champagne='/images/birthday/checkerboard-cheers/experience/sparkling-flute.webp';
const gamePrompts=[
 ['Who’s most likely to…','start the dance floor?','ვის შეუძლია…','პირველმა დაიწყოს ცეკვა?'],
 ['Raise your glass to…','the person who makes you laugh most.','ავწიოთ ჭიქა…','ადამიანისთვის, რომელიც ყველაზე მეტად გაცინებს.'],
 ['Never have I ever…','forgotten the words to my favorite song.','არასოდეს…','დამვიწყებია საყვარელი სიმღერის ტექსტი.'],
 ['Tell us about…','your funniest memory with Alex.','მოგვიყევი…','ალექსთან ყველაზე მხიარული მოგონება.'],
 ['Who’s most likely to…','order one more round of cake?','ვის შეუძლია…','კიდევ ერთი ნაჭერი ტორტი შეუკვეთოს?'],
 ['Make a birthday toast…','in exactly five words.','თქვი სადღეგრძელო…','ზუსტად ხუთი სიტყვით.'],
 ['Cheers if you’ve ever…','danced until the lights came on.','გაგვიმარჯოს, თუ…','გითეკვია შუქების ჩართვამდე.'],
 ['Pass the spotlight…','give the person on your left a compliment.','შენი ჯერია…','შეაქე მარცხნივ მჯდომი ადამიანი.']
];
function Chapter({children,className='',id}){
 const section=useRef(null),scene=useRef(null);
 useLayoutEffect(()=>{let frame;const el=section.current;const measure=()=>{const css=getComputedStyle(el);scene.current.style.setProperty('--fit',Math.min(1,(el.clientHeight-parseFloat(css.paddingTop)-parseFloat(css.paddingBottom))/Math.max(1,scene.current.offsetHeight)));};const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const p=Math.max(-1,Math.min(1,el.getBoundingClientRect().top/innerHeight));el.style.setProperty('--progress',p);});};const ro=new ResizeObserver(measure);ro.observe(el);ro.observe(scene.current);document.fonts.ready.then(measure);window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update();return()=>{ro.disconnect();cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update);};},[]);
 return <section id={id} ref={section} className={`cc-chapter ${className}`}><div ref={scene} className="cc-scene">{children}</div></section>;
}
function calendar(){const data=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//11:11//Birthday//EN','BEGIN:VEVENT','UID:alex-20270608@11-11','DTSTAMP:20261010T000000Z','DTSTART:20270608T150000Z','DTEND:20270608T190000Z','SUMMARY:Alex’s Birthday Party','LOCATION:Tbilisi','END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([data],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='alex-birthday.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Filmstrip({t,motion}){
 const rail=useRef(),drag=useRef(null),dialog=useRef();const [index,setIndex]=useState(0),[view,setView]=useState(null);
 useEffect(()=>{if(view!==null&&!dialog.current.open)dialog.current.showModal();},[view]);
 function move(delta){const next=(index+delta+ribbonPhotos.length)%ribbonPhotos.length;const r=rail.current;const frame=r.children[next];const left=Math.max(0,Math.min(r.scrollWidth-r.clientWidth,frame.offsetLeft-(r.clientWidth-frame.offsetWidth)/2));r.scrollTo({left,behavior:motion?'smooth':'instant'});setIndex(next);}
 return <Chapter id="memories" className="cc-memories"><h2>{t('The good times,\non repeat.','კარგი დრო\nკვლავ და კვლავ.')}</h2><p>{t('Drag to rewind. Swipe for more.','გადაათრიე მოგონებები. გადაფურცლე მეტისთვის.')}</p><div className="cc-film" ref={rail} onScroll={()=>{const r=rail.current;const max=r.scrollWidth-r.clientWidth;if(max>1)setIndex(Math.round(r.scrollLeft/max*2));}} onPointerDown={e=>{if(e.pointerType!=='mouse')return;drag.current={x:e.clientX,left:rail.current.scrollLeft,moved:false};}} onPointerMove={e=>{if(!drag.current)return;const d=e.clientX-drag.current.x;if(Math.abs(d)>5){drag.current.moved=true;rail.current.scrollLeft=drag.current.left-d;}}} onPointerUp={()=>{setTimeout(()=>{drag.current=null;},0);}} onPointerLeave={()=>{drag.current=null;}}>{ribbonPhotos.map((src,i)=><button key={src} className="cc-film-frame" onClick={()=>{if(!drag.current?.moved)setView(i);}} aria-label={t('Open photo: ','ფოტოს ნახვა: ')+ribbonPhotoCaptions[src]}><img src={src} alt={t('An original celebration memory','დღესასწაულის მოგონება')} loading="lazy" draggable="false"/></button>)}</div><div className="cc-film-controls"><button onClick={()=>move(-1)} aria-label={t('Previous photo','წინა ფოტო')}><InvitationArtwork name="arrow-left" size={24}/></button><span aria-live="polite">0{index+1} / 03</span><button onClick={()=>move(1)} aria-label={t('Next photo','შემდეგი ფოტო')}><InvitationArtwork name="arrow-right" size={24}/></button></div><dialog ref={dialog} className="cc-photo-dialog" aria-label={t('Celebration photo','დღესასწაულის ფოტო')} onCancel={()=>setView(null)} onClick={e=>{if(e.target===dialog.current){dialog.current.close();setView(null);}}}><button className="cc-dialog-close" aria-label={t('Close photo','ფოტოს დახურვა')} onClick={()=>{dialog.current.close();setView(null);}}><InvitationArtwork name="close" size={24}/></button>{view!==null&&<img src={ribbonPhotos[view]} alt={t('An original celebration memory','დღესასწაულის მოგონება')}/>}</dialog></Chapter>;
}
function DrinkingGame({t}){
 const [index,setIndex]=useState(0),[revealed,setRevealed]=useState(false);const p=gamePrompts[index];
 const next=()=>{setRevealed(false);setIndex(i=>(i+1)%gamePrompts.length);};
 return <Chapter id="game" className="cc-game"><div><h2>{t('A little sip.\nA lot of stories.','ერთი ყლუპი.\nბევრი ისტორია.')}</h2><p>{t('Take turns. Reveal a card. Make a memory.','ითამაშეთ რიგრიგობით. გახსენით ბარათი. შექმენით მოგონება.')}</p></div><div className="cc-game-area"><button className={`cc-game-card ${revealed?'is-revealed':''}`} aria-label={t(revealed?'Hide party card':'Reveal party card',revealed?'დახურე ბარათი':'გახსენი ბარათი')} aria-pressed={revealed} onClick={()=>setRevealed(v=>!v)}><span className="cc-card-face cc-card-back"><img className="cc-game-cocktail" src={citrusCoupe} alt="" aria-hidden="true"/><span>{t('Here’s to\na good story.','კარგ\nისტორიებს.')}</span><small>{t('Tap to reveal','შეეხე გასახსნელად')}</small></span><span className="cc-card-face cc-card-front"><img className="cc-game-cocktail" src={citrusCoupe} alt="" aria-hidden="true"/><small>{t(p[0],p[2])}</small><strong>{t(p[1],p[3])}</strong><span className="cc-check-mark" aria-hidden="true"/></span></button><div className="cc-game-controls"><button className="cc-button cc-light" onClick={()=>{setIndex(i=>(i+1)%gamePrompts.length);setRevealed(true);}}>{t('Next card','შემდეგი ბარათი')}<InvitationArtwork name="arrow-right" size={20}/></button><button className="cc-button cc-outline" onClick={next}>{t('Skip','გამოტოვება')}</button></div><p className="cc-small">{t('Your drink, your choice.','შენი სასმელი, შენი არჩევანი.')}</p></div></Chapter>;
}
function PartyForm({wish=false,t}){
 const key=`1111-checkerboard-cheers-${wish?'wish':'reply'}:v1`;
 const [saved,setSaved]=useState(()=>{try{const v=JSON.parse(localStorage.getItem(key));return typeof v?.name==='string'&&(wish?typeof v.message==='string':['yes','no'].includes(v.attending))?v:null;}catch{return null;}});
 const [name,setName]=useState(saved?.name||''),[message,setMessage]=useState(saved?.message||''),[attending,setAttending]=useState(saved?.attending||'yes'),[persistent,setPersistent]=useState(true);
 function submit(e){e.preventDefault();if(!name.trim()||(wish&&!message.trim()))return;const value={name:name.trim(),...(wish?{message:message.trim()}:{attending})};try{localStorage.setItem(key,JSON.stringify(value));setPersistent(true);}catch{setPersistent(false);}setSaved(value);}
 return <Chapter id={wish?'wishes':'rsvp'} className={`cc-reply ${wish?'cc-wishes':''}`}><h2>{wish?t('Leave a little\nbirthday love.','დატოვე პატარა\nდაბადების დღის სურვილი.'):t('Your place is waiting.','შენი ადგილი გელოდება.')}</h2><div className="cc-reply-stage"><img className="cc-reply-drink" src={wish?champagne:pinkCitrus} alt="" loading="lazy"/><div className="cc-form-paper">{saved?<div className="cc-confirmation" role="status"><h3>{wish?t('A note to keep.','სამახსოვრო სურვილი.'):saved.attending==='yes'?t('See you at the table!','მაგიდასთან შევხვდებით!'):t('We’ll miss you.','დაგვაკლდები.')}</h3><p>{saved.name}</p>{wish&&<blockquote>{saved.message}</blockquote>}<button className="cc-button" onClick={()=>setSaved(null)}>{t('Edit','შეცვლა')}</button></div>:<form onSubmit={submit}><label htmlFor={`cc-${wish?'wish':'reply'}-name`}>{t('Your name','შენი სახელი')}</label><input id={`cc-${wish?'wish':'reply'}-name`} required pattern=".*\S.*" maxLength={80} autoComplete="given-name" value={name} placeholder={t('e.g. Alex','მაგ. ალექსი')} onChange={e=>setName(e.target.value)}/>{wish?<><label htmlFor="cc-wish-message">{t('Your birthday wish','დაბადების დღის სურვილი')}</label><textarea id="cc-wish-message" required maxLength={600} rows={3} placeholder={t('Write something kind…','დაწერე თბილი სურვილი…')} value={message} onChange={e=>{e.target.setCustomValidity('');setMessage(e.target.value);}} onInvalid={e=>{if(!message.trim())e.target.setCustomValidity(t('Write a birthday wish.','დაწერე სურვილი.'));}}/></>:<fieldset><legend>{t('Will you be there?','შემოგვიერთდები?')}</legend>{['yes','no'].map(v=><label key={v}><input type="radio" name="cc-attendance" checked={attending===v} onChange={()=>setAttending(v)}/>{v==='yes'?t('I’ll be there','მოვდივარ'):t('Can’t make it','ვერ მოვდივარ')}</label>)}</fieldset>}<button className="cc-button" type="submit" onClick={e=>{if(wish&&!message.trim())e.currentTarget.form.querySelector('textarea').setCustomValidity(t('Write a birthday wish.','დაწერე სურვილი.'));}}>{wish?t('Send wish','სურვილის შენახვა'):t('Send my reply','პასუხის შენახვა')}</button></form>}<p className="cc-small">{persistent?t('Preview: replies and wishes stay on this device.','დემო: პასუხები და სურვილები ამ მოწყობილობაზე რჩება.'):t('Saved for this visit only.','შენახულია მხოლოდ ამ ვიზიტისთვის.')}</p></div></div></Chapter>;
}
export default function CheckerboardCheersExperience(){
 const {language}=useLanguage();const t=(en,ka)=>language==='ka'?ka:en;
 const [motion,setMotion]=useState(()=>!matchMedia('(prefers-reduced-motion: reduce)').matches),[toasts,setToasts]=useState(0);const timer=useRef(),[clinking,setClinking]=useState(false);
 useEffect(()=>{window.scrollTo(0,0);const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setMotion(!media.matches);media.addEventListener('change',update);return()=>{clearTimeout(timer.current);media.removeEventListener('change',update);};},[]);
 function go(id){document.getElementById(id)?.scrollIntoView({behavior:motion?'smooth':'instant'});}
 function toast(){clearTimeout(timer.current);setClinking(true);setToasts(n=>n+1);timer.current=setTimeout(()=>setClinking(false),900);}
 return <main lang={language} className={`cc-experience ${motion?'cc-motion':''}`}><div className="cc-opening-wrap"><RibbonSketchToolbar motion={motion} onMotion={()=>setMotion(v=>!v)}/><Chapter className="cc-opening cc-opening-grand"><div className="cc-invitation-paper"><h1>{t('Let the\ngood times\nflow.','კარგი დრო\nახლა\nიწყება.')}</h1><p className="cc-host">{t('Alex turns 28','ალექსი 28 წლის ხდება')}</p><p className="cc-date">{t('8 June 2027','8 ივნისი 2027')} · 19:00 · {t('Tbilisi','თბილისი')}</p><button className="cc-button" onClick={()=>go('plan')}>{t('Pull up a chair','შემოგვიერთდი')}</button></div><div className="cc-opening-glasses" aria-hidden="true"><img className="cc-opening-martini" src={martini} alt=""/><img className="cc-opening-spritz" src={spritz} alt=""/></div></Chapter></div><Chapter id="plan" className="cc-plan"><h2>{t('A night worth\nmaking plans for.','საღამო, რომლისთვისაც\nღირს დაგეგმვა.')}</h2><div className="cc-plan-stage"><div className="cc-menu"><ol>{[t('Hello & a toast','შეხვედრა და სადღეგრძელო'),t('Cake & wishes','ტორტი და სურვილები'),t('One more dance','კიდევ ერთი ცეკვა')].map((text,i)=><li key={i}><time>{['19:00','20:00','21:00'][i]}</time><span>{text}</span></li>)}</ol><button className="cc-button" onClick={calendar}>{t('Add to calendar','კალენდარში დამატება')}</button></div><img src={citrusCoupe} alt="" className="cc-plan-drink" loading="lazy"/></div></Chapter><Chapter id="toast" className="cc-toast"><div className="cc-toast-copy"><h2>{t('Let the\ngood times\nflow.','კარგი დრო\nახლა\nიწყება.')}</h2><p className="cc-host">{t('Alex turns 28','ალექსი 28 წლის ხდება')}</p><p className="cc-date">{t('8 June 2027','8 ივნისი 2027')} · 19:00 · {t('Tbilisi','თბილისი')}</p><button className="cc-button cc-outline" onClick={()=>go('game')}>{t('Let’s celebrate','ვიზეიმოთ')}</button></div><div className="cc-toast-stage"><button className={`cc-clink ${clinking?'is-clinking':''}`} onClick={toast} aria-label={t('Tap the glasses for a toast','შეახე ჭიქები სადღეგრძელოსთვის')}>{drinks.map((src,i)=><img className={`cc-toast-glass cc-glass-${i}`} key={src} src={src} alt="" loading="lazy"/>)}<span className="cc-clink-rays" aria-hidden="true"><i/><i/><i/></span></button><p aria-live="polite">{toasts?t('Here’s to good friends!','კარგ მეგობრებს გაუმარჯოს!'):t('Tap the glasses for a toast','შეეხე ჭიქებს სადღეგრძელოსთვის')}</p></div></Chapter><Filmstrip t={t} motion={motion}/><DrinkingGame t={t}/><PartyForm t={t}/><PartyForm t={t} wish/><footer className="cc-footer"><span>{t('Made by','შექმნილია')}</span><Link to="/" aria-label="11:11"><img src="/logos/logo-pink-star.svg" alt="11:11" width="1330" height="1112"/></Link></footer></main>;
}
