import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { useLanguage } from '../../localization/LanguageContext.jsx';
import RibbonSketchToolbar from '../ribbon-sketch/RibbonSketchToolbar.jsx';
import InvitationArtwork from '../components/InvitationArtwork.jsx';
import { ribbonPhotos } from '../ribbon-sketch/assets.js';
import '../ribbon-sketch/fonts.css';
import '../../styles/pop-disco.css';

const POP_DISCO_BALL='/images/birthday/disco-scrapbook/pop-disco/mirrorball.webp';
const prompts=[
 ['If we could dance anywhere in the world tonight…','Where would it be?','დღეს მსოფლიოს ნებისმიერ ადგილას რომ გვეცეკვა…','სად წავიდოდით?'],
 ['Every great night has a soundtrack.','What’s your dance-floor song?','ყველა კარგ საღამოს თავისი მუსიკა აქვს.','რომელი სიმღერა გაცეკვებს?'],
 ['Pass a little birthday love.','Share your favorite memory with Dea.','გააზიარე დაბადების დღის სითბო.','გაიხსენე დეასთან საყვარელი მოგონება.'],
 ['The spotlight is yours.','Make a birthday toast in five words.','ყურადღების ცენტრში შენ ხარ.','თქვი ხუთსიტყვიანი სადღეგრძელო.'],
 ['Same people. Wilder dreams.','What should we do together next?','იგივე ადამიანები. უფრო დიდი ოცნებები.','შემდეგ რა გავაკეთოთ ერთად?']
];
function DiscoBall({className=''}){return <img className={`pd-ball ${className}`} src={POP_DISCO_BALL} alt="" aria-hidden="true" draggable="false"/>;}
function Chapter({id,className='',children}){
 const root=useRef(),scene=useRef();
 useLayoutEffect(()=>{let raf,alive=true;const el=root.current;const measure=()=>{if(!alive)return;const css=getComputedStyle(el),available=el.clientHeight-parseFloat(css.paddingTop)-parseFloat(css.paddingBottom);scene.current.style.setProperty('--fit',Math.min(1,available/Math.max(1,scene.current.offsetHeight)));};const update=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>el.style.setProperty('--scroll',Math.max(-1,Math.min(1,el.getBoundingClientRect().top/innerHeight))));};const ro=new ResizeObserver(measure);ro.observe(el);ro.observe(scene.current);document.fonts.ready.then(measure);window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update();return()=>{alive=false;ro.disconnect();cancelAnimationFrame(raf);window.removeEventListener('scroll',update);window.removeEventListener('resize',update);};},[]);
 return <section ref={root} id={id} className={`pd-chapter ${className}`}><div ref={scene} className="pd-scene">{children}</div></section>;
}
function Polaroids({t}){
 const dialog=useRef();const [photo,setPhoto]=useState(null);
 useEffect(()=>{if(photo!==null&&!dialog.current.open)dialog.current.showModal();},[photo]);
 const captions=[t('Good times','კარგი დრო'),t('Bigger dreams','დიდი ოცნებები'),t('Still you','ისევ შენ')];
 return <Chapter id="pd-memories" className="pd-memories"><div className="pd-section-head"><h2>{t('Memories\nin the making.','მოგონებები\nიქმნება.')}</h2><p className="pd-kicker">{t('Different moments.\nSame bright you.','სხვადასხვა მომენტი.\nიგივე ნათელი შენ.')}</p></div><div className="pd-polaroids">{ribbonPhotos.map((src,i)=><button key={src} className={`pd-polaroid pd-photo-${i}`} onClick={()=>setPhoto(i)} aria-label={t('Open memory ','მოგონების ნახვა ')+(i+1)}><span className="pd-tape" aria-hidden="true"/><img src={src} alt={captions[i]} loading="lazy"/><span className="pd-hand">{captions[i]}</span></button>)}</div><p className="pd-more pd-hand">{t('More chapters\nto come…','წინ კიდევ\nბევრი ამბავია…')}</p><dialog ref={dialog} className="pd-photo-dialog" aria-label={t('Birthday memory','დაბადების დღის მოგონება')} onCancel={()=>setPhoto(null)} onClick={e=>{if(e.target===dialog.current){dialog.current.close();setPhoto(null);}}}><button className="pd-close" aria-label={t('Close photo','ფოტოს დახურვა')} onClick={()=>{dialog.current.close();setPhoto(null);}}><InvitationArtwork name="close" size={22}/></button>{photo!==null&&<img src={ribbonPhotos[photo]} alt={captions[photo]}/>}</dialog></Chapter>;
}
function Spotlight({t}){
 const [index,setIndex]=useState(0);const p=prompts[index];
 return <Chapter id="pd-spotlight" className="pd-spotlight"><div className="pd-spotlight-stage"><svg className="pd-light-beam" viewBox="0 0 1000 600" preserveAspectRatio="none" aria-hidden="true"><defs><filter id="pd-soft-light" x="-30%" y="-30%" width="160%" height="160%"><feGaussianBlur stdDeviation="14"/></filter><linearGradient id="pd-beam-color" x1="80%" y1="0%" x2="30%" y2="100%"><stop stopColor="#fff2dd" stopOpacity=".78"/><stop offset=".3" stopColor="#f2a8cb" stopOpacity=".88"/><stop offset="1" stopColor="#eda5cc" stopOpacity=".78"/></linearGradient></defs><g filter="url(#pd-soft-light)"><path d="M785 45 C795 180 825 375 844 510 Q840 575 645 554 Q280 530 100 455 Q32 420 104 382 Z" fill="url(#pd-beam-color)"/><ellipse cx="470" cy="465" rx="380" ry="72" transform="rotate(10 470 465)" fill="#f4b3d0" opacity=".44"/></g></svg><h2>{t('Pass the\nspotlight.','ყურადღების\nცენტრში.')}</h2><p className="pd-kicker">{t('Tap the disco ball\nfor a new question','შეეხე დისკოს ბურთს\nახალი კითხვისთვის')}</p><button className="pd-ball-button" onClick={()=>setIndex(i=>(i+1)%prompts.length)} aria-label={t('Reveal next party question','შემდეგი კითხვის ნახვა')}><DiscoBall/></button><div className="pd-prompt" key={index} aria-live="polite"><p className="pd-kicker">{t(p[0],p[2])}</p><p className="pd-hand">{t(p[1],p[3])}</p><InvitationArtwork name="heart" size={28}/></div><p className="pd-explore pd-hand">{t('Tap. Explore.\nShare.','შეეხე. აღმოაჩინე.\nგააზიარე.')}</p><p className="pd-same pd-kicker">{t('Same questions.\nBrighter answers.','იგივე კითხვები.\nუფრო ნათელი პასუხები.')}</p></div></Chapter>;
}
function useSavedNote(kind){
 const key=`1111-pop-disco-${kind}:v1`;
 const [saved,setSaved]=useState(()=>{try{const v=JSON.parse(localStorage.getItem(key));return typeof v?.name==='string'&&(kind==='wish'?typeof v.message==='string':['yes','no'].includes(v.attendance))?v:null;}catch{return null;}});
 const [persistent,setPersistent]=useState(true);
 const save=value=>{try{localStorage.setItem(key,JSON.stringify(value));setPersistent(true);}catch{setPersistent(false);}setSaved(value);};
 return {saved,save,edit:()=>setSaved(null),persistent};
}
function PreviewNote({persistent,t}){return <p className="pd-preview">{persistent?t('Preview: saved on this device.','დემო: ინახება ამ მოწყობილობაზე.'):t('Saved for this visit only.','შენახულია მხოლოდ ამ ვიზიტისთვის.')}</p>;}
function RSVP({t}){
 const {saved,save,edit,persistent}=useSavedNote('reply');const [name,setName]=useState(saved?.name||''),[attendance,setAttendance]=useState(saved?.attendance||'yes'),[note,setNote]=useState(saved?.note||'');
 function submit(e){e.preventDefault();if(!name.trim())return;save({name:name.trim(),attendance,note:note.trim()});}
 return <Chapter id="pd-rsvp" className="pd-rsvp"><DiscoBall className="pd-rsvp-ball"/><div className="pd-section-head"><h2>RSVP</h2><p className="pd-kicker">{t('Can’t wait\nto celebrate together.','მოუთმენლად ველი\nერთად აღნიშვნას.')}</p></div><div className="pd-rsvp-layout"><div className="pd-rsvp-paper">{saved?<div className="pd-saved" role="status"><h3>{saved.attendance==='yes'?t('See you on\nthe dance floor.','საცეკვაო მოედანზე\nშევხვდებით.'):t('You’ll be missed.','დაგვაკლდები.')}</h3><p>{saved.name}</p><button className="pd-button" onClick={edit}>{t('Edit RSVP','პასუხის შეცვლა')}</button></div>:<form onSubmit={submit}><label htmlFor="pd-name">{t('Your name','შენი სახელი')}</label><input id="pd-name" autoComplete="given-name" required pattern=".*\S.*" maxLength={80} placeholder={t('e.g. Dea','მაგ. დეა')} value={name} onChange={e=>setName(e.target.value)}/><fieldset><legend>{t('Will you be joining?','შემოგვიერთდები?')}</legend>{['yes','no'].map(v=><label key={v}><input type="radio" name="pd-attendance" checked={attendance===v} onChange={()=>setAttendance(v)}/>{v==='yes'?t('Yes, I’ll be there!','კი, მოვდივარ!'):t('Sadly, I can’t make it','სამწუხაროდ, ვერ მოვდივარ')}</label>)}</fieldset><label htmlFor="pd-note">{t('Any special notes?','დამატებითი შენიშვნა?')}</label><textarea id="pd-note" rows={2} maxLength={400} placeholder={t('Dietary requirements, a song request…','კვების სურვილი, საყვარელი სიმღერა…')} value={note} onChange={e=>setNote(e.target.value)}/><button className="pd-button" type="submit">{t('Send RSVP','პასუხის შენახვა')}<InvitationArtwork name="arrow-right" size={18}/></button></form>}<PreviewNote persistent={persistent} t={t}/></div><p className="pd-hand pd-rsvp-hand">{t('Good\npeople\ncount.','კარგი\nადამიანები\nმნიშვნელოვანია.')}<InvitationArtwork name="heart" size={28}/></p></div><p className="pd-rsvp-footer pd-kicker">{t('Same people.\nBrighter times.','იგივე ადამიანები.\nუფრო ნათელი დრო.')}</p></Chapter>;
}
function Guestbook({t}){
 const {saved,save,edit,persistent}=useSavedNote('wish');const [name,setName]=useState(saved?.name||''),[message,setMessage]=useState(saved?.message||'');
 function submit(e){e.preventDefault();if(!name.trim()||!message.trim())return;save({name:name.trim(),message:message.trim()});}
 return <Chapter id="pd-wishes" className="pd-wishes"><div className="pd-section-head"><h2>{t('Birthday\nwishes.','დაბადების დღის\nსურვილები.')}</h2><p className="pd-kicker">{t('Kind words.\nBrighter tomorrows.','თბილი სიტყვები.\nნათელი ხვალინდელი დღე.')}</p></div><div className="pd-book"><span className="pd-book-ribbon" aria-hidden="true"/><span className="pd-book-charm" aria-hidden="true"><DiscoBall/></span><span className="pd-book-stars" aria-hidden="true"><InvitationArtwork name="star" size={38}/><InvitationArtwork name="star" size={28}/></span><div className="pd-book-left">{saved?<div className="pd-book-saved" role="status"><p className="pd-hand">{t('A note to keep.','სამახსოვრო სურვილი.')}</p><blockquote>{saved.message}</blockquote><p className="pd-hand">{saved.name}</p><button className="pd-text-button" onClick={edit}>{t('Edit your wish','სურვილის შეცვლა')}</button></div>:<form onSubmit={submit}><p className="pd-hand">{t('Leave a message\nfor Dea…','დატოვე სურვილი\nპრისცილასთვის…')}</p><label className="pd-sr-only" htmlFor="pd-wish-name">{t('Your name','შენი სახელი')}</label><input id="pd-wish-name" required pattern=".*\S.*" maxLength={80} placeholder={t('Your name','შენი სახელი')} value={name} onChange={e=>setName(e.target.value)}/><label className="pd-sr-only" htmlFor="pd-wish-message">{t('Your birthday wish','დაბადების დღის სურვილი')}</label><textarea id="pd-wish-message" rows={3} required maxLength={400} placeholder={t('Your message…','შენი სურვილი…')} value={message} onChange={e=>{e.target.setCustomValidity('');setMessage(e.target.value);}}/><button className="pd-text-button" type="submit" onClick={e=>{if(!message.trim())e.currentTarget.form.querySelector('textarea').setCustomValidity(t('Write a birthday wish.','დაწერე სურვილი.'));}}>{t('Send wish','სურვილის შენახვა')}<InvitationArtwork name="arrow-right" size={18}/></button></form>}</div><div className="pd-book-right"><p className="pd-hand">{t('Here’s to\nmore dancing,\nmore dreaming,\nmore of you.','მეტი ცეკვა,\nმეტი ოცნება,\nმეტი შენ.')}<InvitationArtwork name="heart" size={32}/></p></div></div><PreviewNote persistent={persistent} t={t}/><p className="pd-book-tag pd-kicker">{t('Big dreams.\nKind people.\nHappy 33.','დიდი ოცნებები.\nკარგი ადამიანები.\nბედნიერი 33.')}</p></Chapter>;
}
export default function PopDiscoExperience(){
 const {language}=useLanguage();const t=(en,ka)=>language==='ka'?ka:en;const [motion,setMotion]=useState(()=>!matchMedia('(prefers-reduced-motion: reduce)').matches);
 useEffect(()=>{window.scrollTo(0,0);const media=matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setMotion(!media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 return <main lang={language} className={`pd-experience ${motion?'pd-motion':''}`}><div className="pd-opening"><RibbonSketchToolbar motion={motion} onMotion={()=>setMotion(v=>!v)}/><Chapter id="pd-opening" className="pd-hero"><DiscoBall className="pd-hero-ball"/><div className="pd-hero-copy"><p className="pd-invited">{t('You’re invited','მოწვეული ხარ')}</p><h1><span>{t('Dea','დეა')}</span><span>{t('turns 33.','ხდება 33.')}</span></h1><p className="pd-date">{t('2 September 2027','2 სექტემბერი 2027')}<br/>19:00<br/>{t('Tbilisi','თბილისი')}</p><p className="pd-hero-hand pd-hand">{t('Same\ndance floor,\nwilder dreams.','იგივე\nსაცეკვაო მოედანი,\nუფრო დიდი ოცნებები.')}</p></div><a className="pd-hero-note pd-kicker" href="#pd-lineup">{t('Good people.\nBrighter nights.','კარგი ადამიანები.\nნათელი ღამეები.')}<InvitationArtwork name="arrow-down" size={22}/></a></Chapter></div><Chapter id="pd-lineup" className="pd-lineup"><div className="pd-section-head"><h2>{t('The\nevening lineup.','საღამოს\nპროგრამა.')}</h2><p className="pd-kicker">{t('Good music.\nGood company.\nGreat at 33.','კარგი მუსიკა.\nკარგი ადამიანები.\nსაუკეთესო 33.')}</p></div><div className="pd-ticket"><p className="pd-ticket-stub pd-kicker">{t('Dea\nturns 33','დეა\nხდება 33')}</p><ol>{[["19:00",t('Doors &\nwelcome drinks','შეხვედრა და\nსასმელები'),'circle-dot',t('Meet','შეხვედრა')],["20:00",t('Dinner &\ntoasts','ვახშამი და\nსადღეგრძელო'),'heart',t('Celebrate','აღნიშვნა')],["21:30",t('Dance floor\nopens','ცეკვა\nიწყება'),'play',t('Dance','ცეკვა')],[t('LATE','გვიან'),t('More music.\nMore magic.','მეტი მუსიკა.\nმეტი მაგია.'),'sparkle',t('Repeat','გამეორება')]].map(([time,copy,icon,label])=><li key={time}><time>{time}</time><p>{copy}</p><InvitationArtwork name={icon} size={38}/><small>{label}</small></li>)}</ol><p className="pd-ticket-stub pd-ticket-end pd-kicker">{t('All good\npeople','ყველა კარგი\nადამიანი')}</p></div><p className="pd-lineup-hand pd-hand">{t('Same night,\ndifferent level.','იგივე საღამო,\nსხვა დონე.')}<InvitationArtwork name="heart" size={28}/></p></Chapter><Polaroids t={t}/><Spotlight t={t}/><RSVP t={t}/><Guestbook t={t}/><footer className="pd-footer"><p className="pd-kicker">{t('Special people.\nSpecial moments.\nAlways a reason to dance.','განსაკუთრებული ადამიანები.\nგანსაკუთრებული მომენტები.\nცეკვის მიზეზი ყოველთვის არის.')}</p><div><span>{t('Made by','შექმნილია')}</span><Link to="/" aria-label="11:11"><img src="/logos/logo-pink-star.svg" alt="11:11" width="90" height="75"/></Link></div><p className="pd-kicker">{t('Birthdays\nhit different\naround here.','დაბადების დღე\nაქ ყოველთვის\nგანსაკუთრებულია.')}<InvitationArtwork name="heart" size={26}/></p></footer></main>;
}
