import { captionValue } from "../../localization/captionValues.js";
import RibbonSketchToolbar from '../ribbon-sketch/RibbonSketchToolbar.jsx';
import SnakeGame from '../y2k/SnakeGame.jsx';
import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { useLanguage } from '../../localization/LanguageContext.jsx';
import InvitationArtwork from '../components/InvitationArtwork.jsx';
import { CDCatch } from '../y2k/Y2KGames.jsx';
import { RSVPForm, Soundtrack } from '../y2k/Y2KForms.jsx';
import useY2KMotion from '../y2k/useY2KMotion.js';
import '../ribbon-sketch/fonts.css';
import '../../styles/y2k-experience.css';

const assets = '/images/birthday/y2k-experience/';
const memories = ['/images/bridal/party-polaroids/sky-toast.webp', '/images/bridal/party-polaroids/champagne-spray.webp', '/images/bridal/party-polaroids/shadow-toast.webp'];

function Window({ title, icon = 'image', className = '', children }) {
  return <div className={`y2k-window ${className}`}><div className="y2k-window-bar"><span><InvitationArtwork name={icon} size={16} />{title}</span><span className="y2k-window-decoration" aria-hidden="true"><InvitationArtwork name="minus" size={12} /><InvitationArtwork name="image" size={12} /><InvitationArtwork name="close" size={12} /></span></div>{children}</div>;
}

function PartyDetails({ t, sleepover }) {
 const { language } = useLanguage();

  const details = [
    ['calendar', captionValue("invitations.pages.Y2KPartyExperience.caption1", language), captionValue("invitations.pages.Y2KPartyExperience.caption2", language), captionValue("invitations.pages.Y2KPartyExperience.caption3", language)],
    ['clock', captionValue("invitations.pages.Y2KPartyExperience.caption4", language), '19:00', captionValue("invitations.pages.Y2KPartyExperience.caption5", language)],
    ['map-pin', captionValue("invitations.pages.Y2KPartyExperience.caption6", language), captionValue("invitations.pages.Y2KPartyExperience.caption7", language), captionValue("invitations.pages.Y2KPartyExperience.caption8", language)],
    ['sparkle', captionValue("invitations.pages.Y2KPartyExperience.caption9", language), sleepover ? captionValue("invitations.pages.Y2KPartyExperience.caption10", language) : captionValue("invitations.pages.Y2KPartyExperience.caption11", language), sleepover ? captionValue("invitations.pages.Y2KPartyExperience.caption12", language) : captionValue("invitations.pages.Y2KPartyExperience.caption13", language)],
  ];
  return <dl className="y2k-details-list">{details.map(([icon, label, value, note]) => <div key={icon} data-y2k-reveal><InvitationArtwork name={icon} size={29} /><dt className="y2k-mono">{label}</dt><dd>{value}<small>{note}</small></dd></div>)}</dl>;
}

export default function Y2KPartyExperience({ theme = 'arcade' }) {
  const { language } = useLanguage();
  const t = (captionKey, values) => captionValue(captionKey, language, values);
  const sleepover = theme === 'sleepover';
  const root = useRef(null);
  const [motion, setMotion] = useState(() => !window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  useY2KMotion(root, theme, motion);
  useEffect(() => { const media = window.matchMedia('(prefers-reduced-motion: reduce)'); const change = () => setMotion(!media.matches); media.addEventListener('change', change); return () => media.removeEventListener('change', change); }, []);

  return <main ref={root} lang={language} className={`y2k-experience y2k-${theme} ${motion ? 'y2k-motion' : ''}`}>
    <a className="y2k-skip" href="#y2k-rsvp">{captionValue("invitations.pages.Y2KPartyExperience.caption14", language)}</a>
    <RibbonSketchToolbar showMotion={false} playHref="#y2k-play" />

    {sleepover ? <section className="y2k-hero y2k-sleep-hero" aria-labelledby="y2k-title"><div className="y2k-wrap"><div className="y2k-sleep-heading"><p className="y2k-mono">{captionValue("invitations.pages.Y2KPartyExperience.caption15", language)}</p><h1 id="y2k-title">DESKTOP<br className="y2k-mobile-break" /> SLEEPOVER</h1><p className="y2k-hand">{captionValue("invitations.pages.Y2KPartyExperience.caption16", language)}<InvitationArtwork name="heart" size={23} /></p></div><div className="y2k-sleep-desktop"><Window title="invitation.jpg" className="y2k-sleep-photo"><img src={`${assets}sleepover-satin.png`} alt={captionValue("invitations.pages.Y2KPartyExperience.caption17", language)} width="1536" height="1024" fetchPriority="high" /><div className="y2k-photo-caption"><p className="y2k-hand">{captionValue("invitations.pages.Y2KPartyExperience.caption18", language)}</p><p className="y2k-mono">24.10.2027 / 19:00 / {captionValue("invitations.pages.Y2KPartyExperience.caption19", language)}</p></div></Window><Window title={captionValue("invitations.pages.Y2KPartyExperience.caption20", language)} icon="mail" className="y2k-message"><div className="y2k-message-envelope"><p><span>From:</span>{captionValue("invitations.pages.Y2KPartyExperience.caption21", language)}</p><p><span>To:</span>{captionValue("invitations.pages.Y2KPartyExperience.caption22", language)}</p></div><div className="y2k-message-content"><p>{captionValue("invitations.pages.Y2KPartyExperience.caption23", language)}</p><p>{captionValue("invitations.pages.Y2KPartyExperience.caption24", language)}</p><p className="y2k-hand">{captionValue("invitations.pages.Y2KPartyExperience.caption25", language)}<InvitationArtwork name="heart" size={20} /></p><a className="y2k-button" href="#y2k-rsvp">{captionValue("invitations.pages.Y2KPartyExperience.caption26", language)}<InvitationArtwork name="arrow-right" size={18} /></a></div></Window></div><a className="y2k-scroll-note y2k-mono" href="#y2k-details">{captionValue("invitations.pages.Y2KPartyExperience.caption27", language)}<InvitationArtwork name="arrow-down" size={18} /></a></div></section>
      : <section className="y2k-hero y2k-arcade-hero" aria-labelledby="y2k-title"><div className="y2k-wrap y2k-hero-grid"><div className="y2k-hero-copy"><p className="y2k-mono">{captionValue("invitations.pages.Y2KPartyExperience.caption28", language)}</p><h1 id="y2k-title"><span>Y2K</span><span>PARTY</span></h1><p className="y2k-hero-invited">{captionValue("invitations.pages.Y2KPartyExperience.caption29", language)}</p><div className="y2k-hero-actions"><a href="#y2k-play" className="y2k-button y2k-button-outline">{captionValue("invitations.pages.Y2KPartyExperience.caption30", language)}<InvitationArtwork name="play" size={18} /></a><a href="#y2k-rsvp" className="y2k-button">{captionValue("invitations.pages.Y2KPartyExperience.caption31", language)}<InvitationArtwork name="arrow-up-right" size={18} /></a></div></div><div className="y2k-hero-art"><div className="y2k-case"><img src={`${assets}invitation-case.png`} alt={captionValue("invitations.pages.Y2KPartyExperience.caption32", language)} width="1632" height="976" fetchPriority="high" /><div className="y2k-case-copy"><p className="y2k-hand">{captionValue("invitations.pages.Y2KPartyExperience.caption33", language)}</p><span className="y2k-mono">BIRTHDAY<br />MIX / VOL. 01</span><strong>24 OCT</strong><span className="y2k-mono">19:00 / {captionValue("invitations.pages.Y2KPartyExperience.caption34", language)}</span></div></div><div className="y2k-hero-art-footer"><span className="y2k-mono">{captionValue("invitations.pages.Y2KPartyExperience.caption35", language)}</span><p className="y2k-hand">{captionValue("invitations.pages.Y2KPartyExperience.caption36", language)}</p></div></div></div><a className="y2k-scroll-note y2k-mono" href="#y2k-details">{captionValue("invitations.pages.Y2KPartyExperience.caption37", language)}<InvitationArtwork name="arrow-down" size={18} /></a></section>}

    <section id="y2k-details" className="y2k-section y2k-details"><div className="y2k-wrap"><div className="y2k-section-heading" data-y2k-reveal><h2>{captionValue("invitations.pages.Y2KPartyExperience.caption38", language)}</h2><p className="y2k-mono">{captionValue("invitations.pages.Y2KPartyExperience.caption39", language)}</p></div>{sleepover ? <Window title="party-plans.txt" icon="calendar"><PartyDetails t={t} sleepover /></Window> : <PartyDetails t={t} />}<p className="y2k-details-foot y2k-hand" data-y2k-reveal>{sleepover ? captionValue("invitations.pages.Y2KPartyExperience.caption40", language) : captionValue("invitations.pages.Y2KPartyExperience.caption41", language)}<InvitationArtwork name={sleepover ? 'heart' : 'star'} size={26} /></p></div></section>

    <section id="y2k-play" className="y2k-section y2k-play-section"><div className="y2k-wrap y2k-play-layout"><div className="y2k-play-copy" data-y2k-reveal><p className="y2k-mono">{sleepover ? 'A LITTLE NOSTALGIA' : 'MINI GAMES. MAX GOOD TIMES.'}</p><h2>{sleepover ? captionValue("invitations.pages.Y2KPartyExperience.caption42", language) : captionValue("invitations.pages.Y2KPartyExperience.caption43", language)}</h2><p>{sleepover ? captionValue("invitations.pages.Y2KPartyExperience.caption44", language) : captionValue("invitations.pages.Y2KPartyExperience.caption45", language)}</p><a className="y2k-game-skip" href="#y2k-music">{captionValue("invitations.pages.Y2KPartyExperience.caption46", language)}<InvitationArtwork name="arrow-right" size={18} /></a></div><div data-y2k-reveal className="y2k-play-stage" key={theme}>{sleepover ? <Window title="snake.exe" icon="play"><SnakeGame t={t} /></Window> : <CDCatch t={t} />}</div></div></section>

    <section id="y2k-music" className="y2k-section y2k-music-section"><div className="y2k-wrap"><div className="y2k-section-heading" data-y2k-reveal><h2>{captionValue("invitations.pages.Y2KPartyExperience.caption47", language)}</h2><p className="y2k-hand">{captionValue("invitations.pages.Y2KPartyExperience.caption48", language)}<InvitationArtwork name="heart" size={24} /></p></div><div data-y2k-reveal>{sleepover ? <Window title="now-playing.mp3" icon="play"><Soundtrack t={t} eventId={sleepover ? "desktop-sleepover" : "y2k"} /></Window> : <Soundtrack t={t} eventId={sleepover ? "desktop-sleepover" : "y2k"} />}</div></div></section>

    {sleepover && <section className="y2k-section y2k-memories"><div className="y2k-wrap"><div className="y2k-section-heading" data-y2k-reveal><h2>{captionValue("invitations.pages.Y2KPartyExperience.caption49", language)}</h2><p className="y2k-mono">{captionValue("invitations.pages.Y2KPartyExperience.caption50", language)}</p></div><div className="y2k-polaroids">{memories.map((src, i) => <figure key={src} data-y2k-reveal style={{ '--photo-angle': `${[-5, 4, -3][i]}deg`, '--reveal-delay': `${i * 100}ms` }}><img src={src} alt={[captionValue("invitations.pages.Y2KPartyExperience.caption51", language), captionValue("invitations.pages.Y2KPartyExperience.caption52", language), captionValue("invitations.pages.Y2KPartyExperience.caption53", language)][i]} loading="lazy" width="600" height="700" /><figcaption className="y2k-hand">{[captionValue("invitations.pages.Y2KPartyExperience.caption54", language), captionValue("invitations.pages.Y2KPartyExperience.caption55", language), captionValue("invitations.pages.Y2KPartyExperience.caption56", language)][i]}</figcaption></figure>)}</div></div></section>}

    <section id="y2k-rsvp" className="y2k-section y2k-rsvp-section"><div className="y2k-wrap y2k-rsvp-layout"><div className="y2k-rsvp-copy" data-y2k-reveal><h2>RSVP</h2><p className="y2k-mono">{captionValue("invitations.pages.Y2KPartyExperience.caption57", language)}</p><p className="y2k-hand">{captionValue("invitations.pages.Y2KPartyExperience.caption58", language)}<InvitationArtwork name="heart" size={30} /></p></div><div data-y2k-reveal>{sleepover ? <Window title="rsvp.message" icon="mail"><RSVPForm t={t} eventId={sleepover ? "desktop-sleepover" : "y2k"} /></Window> : <RSVPForm t={t} eventId={sleepover ? "desktop-sleepover" : "y2k"} />}</div></div></section>

    <div className="y2k-footer"><div className="y2k-wrap"><div className="y2k-footer-top" data-y2k-reveal><h2>{sleepover ? captionValue("invitations.pages.Y2KPartyExperience.caption59", language) : captionValue("invitations.pages.Y2KPartyExperience.caption60", language)}</h2><InvitationArtwork name={sleepover ? 'heart' : 'star'} size={72} /></div></div></div><footer className="y2k-maker-credit"><span>{captionValue("invitations.pages.Y2KPartyExperience.caption61", language)}</span><Link to="/" aria-label={captionValue("invitations.pages.Y2KPartyExperience.caption62", language)}><img src="/logos/logo-pink-star.svg" alt="11:11" width="1330" height="1112" /></Link></footer>
  </main>;
}
